### ISSUE TITLE
Need some modification in development.ini file

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1160]
At present

In development.ini you have this config:
- `session.secret = change_this_value_please!`
- `api.key = changethisnow!`
- `email.reply.token` is replaced by `api.key`

Expected

- [x] When you want to start tracim you need to have changed the `session.secret`  key: 
- [X] ~~Default `api.key` value must be empty and authentication based on api key must return false if `api key` is empty.~~ done in PR #1188
- [x] For docker image: generate an randomized key for this 2 key: `session.secret` and `api.key` 
- [X] ~~remove line about `email.reply.token` in development.ini~~ done in PR #1188

- [X] ~~remove config about `email.reply.token` in config.py~~ done in PR #1188

**Comment by PhilippeAccorsi** [comment]
Verified.
