### ISSUE TITLE
[META] Bug: Long user name breaks page rendering

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#197]
## Description and expectations

Expected to better handle a long user name:

- [ ] We can't see the end of the name in the main header. When you click on it to access the menu, the menu appears off the screen. 
![S3g60CK](https://user-images.githubusercontent.com/35422692/147342392-b3d58e03-4ecd-452c-81c3-9b85a3620e3f.png)
(This is not the cut of the screenshot, but the border of the application.)
- [ ] If the user has a name or username that is too long, they stick out on both sides in the account settings. It is possible to scroll horizontally (but you go out of the application) to see the end of the name on the right. Impossible on the left.
![S8TrK5b](https://user-images.githubusercontent.com/35422692/147345008-5026bff5-255c-4de6-800e-c650067487d1.png)
(big name)
![hhYhE61](https://user-images.githubusercontent.com/35422692/147344997-20ff4b79-79b8-4af4-b1d7-f8977455e23e.png)
(big username)
- [ ] When changing for a new name that is too large, the user feedback error message is not explicit. Contents of error 400 in the console: `public_name: ["Length must be between 3 and 255."]`. Suggestion : Display this directly in the edit line before pressing submit, like a double check, one by the front followed by one by the back
- [ ] In the public profile if the user has a name or a login that is too long, they stick out to the right
![FXWuHFg](https://user-images.githubusercontent.com/35422692/147345325-f809e559-c17b-4eb4-be07-f213a33c6a0c.png)
- [ ] In recent activities if the user has a too big name, you can't see the content name. Maybe fix (not sure, to check) with the [fix/5181__no_clickable_tooltip_space_content](https://github.com/tracim/tracim/commits/fix/5181__no_clickable_tooltip_space_content) (commit [b1573fd](https://github.com/tracim/tracim/commit/b1573fde56fc7182b976251c76c7c3f36b15739a)) branch
![ASz3pFQ](https://user-images.githubusercontent.com/35422692/147345458-9381aa95-f60e-44ae-ad48-351b4c2eeb11.png)
- [ ] In the timeline revisions, if the user has a name that is too large without a space, the text goes out of the card.
![HYIgB9Y](https://user-images.githubusercontent.com/35422692/147345562-d1a84380-d7a7-467f-a820-f9f1456e7de8.png)
- [ ] In the timeline revisions, if the user has a name that is too large with white spaces, the text overlaps between the cards.
![AI7dJGg](https://user-images.githubusercontent.com/35422692/147345662-985c400d-1dd4-45ac-803c-4b0e6f44a232.png)
- [ ] In the user administration page, it misses `...` when the name of a user is too big without spaces. If the name has spaces there is a line break.
![b3k4TpE](https://user-images.githubusercontent.com/35422692/147345877-f113dcfa-b7e3-462c-9972-37c67fc48b2f.png)

### How to reproduce

(systematic)
1. Go to account settings
2. Change for a very big user name
3. Go to it indicated place

### Version information

- Tracim version: v4.1
- Web browser: Brave
- Device / System: PC

________________________________________________

## Prerequisites

None
