### ISSUE TITLE
Add a unique username to users

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2829]
## Feature description (short)

There is a need for users to have a username which is unique and spaceless (ie does not contain any space char).

This username will allow to search a user, to login and (in the near future) to mention it in a comment or content.

*note : this issue is both frontend and backend. If you want to split the execution, you can add issues associated to this*

## Target branch for developments

    feature/2829__unique_user_username

## Context

Currently, the unique key for identifying a user is the email address. This is a constraint or two reasons:

1. it requires to use tracim with users having an email, even if email notifications are deactivated.
2. typing an email address on a smartphone is long and inefficient. A standard username would be more simple

Another problem is we will implement mentions feature which allow to mention a user in a comment or in a content. The easiest way to do so is to have a `@somebody` mechanism based on a "spaceless" unique username.

## Feature description (long)

Adding a username field in the backend database
The field in database must be unique and not null

- [x] username is in table user
- [x] api returns the username

This issue will only add the field in database and to the users related endpoints.

Translation and naming: 
- in API, keep public_name and add username fields
- in user interface, keep Full name (Nom complet - Nome completo) and add username
    - English: username
    - French: identifiant
    - Portuguese: identificador

### Frontend

- [x] Allow to login with username -> #2927
    - Update placeholder, input icon and flash messages with the errors
    - Check if autocomplete of login still works with username
- [x] Allow to reset password from username -> #2940
    - Update placeholder, icon and add a new check to see if the username is linked to a email. If not, add a new error screen (such as the screen for notifications by emails not activated) or a flash message with the error.
- [x] On the admin screens (requires API to be updated): -> #2945 
    - Add username field in the table that when it is null it will be empty, same for the field E-mail
    - For create new user: add a username field, a warning about e-mails/reset password (question mark icon next to the email label) and add a warning message for non-standard or non-unique usernames
    - Rule for username: allowed chars: `azAZ09-_` and minimal lenght of 3 chars (sometimes the user will enter @username, sometimes just username, the frontend should handle both cases)
    - Use the endpoint to check availability of a username
    - Add a warning when the user is created if the email field is empty and the notifications are activated
- [x] Allow NULL value for email and username but never both being NULL at the same time (some check must be implemented on frontend too) -> #2945
    - At forms, the submit button should be disabled if both fields are empty
- [x] At account Settings (My Account or a user's page in Admins view): -> #2943
    - Add username in user information, at "My profile" add a username field and add a warning about changing the username field
    - Rule for username: allowed chars: `azAZ09-_` and minimal lenght of 3 chars (sometimes the user will enter @username, sometimes just username, the frontend should handle both cases)
    - Use the endpoint to check availability of a username
- [x] If username is NULL (taken from API response), suggest user to set username at login time
    - A simple popup which can be skipped (checkbox "don't show me again" if the user does not want to setup a username) -> #2950 
- [x] User can change his own username but a warning will tell him that all old mentions will be broken -> #2943 
- [x] Change the on Add a member (dashboard and advanced dashboard) the text and the placeholder -> #2930 
- [x] Anonymization process: verify that interface is not broken if username is NULL
- [x] Add username in the `user` object of the redux state -> #2917 

### Backend

- [x] All APIs returning `public_name` should also return `username` now. -> #2933 
- [x] Allow to login with username -> #2933
- [x] Allow NULL value for email and username but never both being NULL at the same time (database + lib checks) -> #2933 
- [x] Allow login (api) through email or username -> #2933 
- [x] Allow login (webdav) through email or username -> #3060
- [x] Allow LDAP mapping with email, username, public_name (NULL email and/or username is ok)
- [x] Anonymization process: -> #3061
    - [x] Keep public name like in current version (keep **anonymised public_name**)
    - [x] Username set to NULL
- [x] Username is unique, email is unique, public_name is not unique, rule for username: allowed chars: `azAZ09-_` and minimal lenght of 3 chars -> #2933
- [x] A endpoint allow to check availability of a username (it says true or false, no detail) -> #2933
- [x] Username minimal lenght is 3 chars -> #2933
- [x] If no email address, the backend should not crash, just ignore notification to send -> #2933
- [x] Username can be modified: modification must be with an api like email, which require sending password; admin must be able to change other user usernames with it's own password  -> #2933
- [x] Allow to `post` reset password with username or email, new code error to username not linked to any email -> #3020
- [x] migration scripts -> #3048
- [x] Add a configuration in backend configuration file, like `allow_empty_password = False`, that refuse empty email (should be the default behavior) -> #3047
- [x] Add support for username in tracimcli command line at the same place than email (support login, not specifically email).  -> #3061
- [x] Anonymisation or delete of a user will result in showing "Deleted User" as author of something -> #3050 

## Impacted components

- database (including migration script)
- backend
  - api
  - webdav
  - ldap
  - email notifications
- frontend
  - frontend_lib
  - frontend_app_admin_workspace_user
  - frontend
  - frontend_app_workspace_advanced

**Comment by inkhey** [comment]
Problem to clarify about this:
- When the user will set his username for the first time ?
- Can the user modify it ?
- If the user cannot modify his username, how to handle user from previous tracim version which have unclear username
- same for user that are automatically created from external auth/ ldap.

What i suggest:
- allow user without username.
- user are created without username.
- for user without username, add pop up or something to suggest them to set the value with correct ui
- refuse user to change their fixed username.
- conserve public name as "real name", username is an identifiant, it's not really nice to be named "john43323".

**Comment by lebouquetin** [comment]
@Skylsmoi @inkhey could you complete the list of public services and changeability of username ?

**Comment by lebouquetin** [comment]
> - allow user without username.
> - user are created without username.

This will not allow uniqueness, which is a problem. (every user would be able to impersonate another user by choosing same username)

**Comment by lebouquetin** [comment]
Finally I suggest:

- username is unique, public name is not
- user can change his own username but a warning will tell him that all old mentions will be broken
- migration is done by setting automatically a username like user123.
- on login, if the username is `userxxx` the user is redirected to his profile page and requested to choose a valid username (or a popup ask him to choose a nickname with a message like : "starting with tracim 3 a mechanism will allow to mention you in comments and contents. Tracim need you to choose your username)
- a endpoint allow to check availability of a username (it says true or false, no detail)
- username minimal lenght is 3 chars
- email is not unique anymore
- account creation allow to not set an email (in this case users will not get notifications

What do you think @Skylsmoi @gbonaspetti @celiamgtt @inkhey @PhilippeAccorsi @raphj

**Comment by celiamgtt** [comment]
Just one question, why allowed several accounts with the same email address?

**Comment by inkhey** [comment]
> > * allow user without username.
> > * user are created without username.
> 
> This will not allow uniqueness, which is a problem. (every user would be able to impersonate another user by choosing same username)

Standard SQL allow multiple null value with "Unique" field.

**Comment by inkhey** [comment]
>     * email is not unique anymore
>     * account creation allow to not set an email (in this case users will not get notifications
>
> What do you think @Skylsmoi @gbonaspetti @celiamgtt @inkhey @PhilippeAccorsi @raphj

I see some problem with making email not unique anymore:
- We can't login anymore with email
- LDAP code rely currently on email, we need to rework it.

**Comment by lebouquetin** [comment]
> Standard SQL allow multiple null value with "Unique" field, so i don't see the problem.

I'm pretty sure it's not the case with all supported databases... I'd like you to try this, if its ok, so we can set NULL as default username, otherwise we set default value to `userxxx` with xxx being the `user_id`.

**Comment by Skylsmoi** [comment]
> Just one question, why allow several accounts with the same email address?

I don't see the advantages either, even if it's technically possible, it doesn't mean we have to do it

**Comment by raphj** [comment]
We could allow logging in when the email address is used once in a first time, and show a list of accounts if it is not in a second time. WebDAV will also have to allow using the username.

**Comment by lebouquetin** [comment]
> - We can't login anymore with email

@inkhey @celiamgtt I'd like to allow using tracim without email. In this case, we need an empty/null value. If all supported databases allow several NULL values, then we can keep the uniqueness of the email.

> LDAP code rely currently on email, we need to rework it.

So I think the email uniqueness must be kept... if so, is there still rework of LDAP support? I'd like we can connect LDAP mapped to username or email (or both)

**Comment by lebouquetin** [comment]
@raphj using the email as webdav user does not prevent from loging with a url like `davs://username@server/path`: if this does not work, it's the client implementation which is wrong

**Comment by Skylsmoi** [comment]
> on login, if the username is userxxx the user is redirected to his profile page and requested to choose a valid username (or a popup ask him to choose a nickname with a message like : "starting with tracim 3 a mechanism will allow to mention you in comments and contents. Tracim need you to choose your username)

That mean we will have code in frontend which only usage is to handle a specific migration process. That's not ideal because this code will end up dead at some point.
We must not forget to remove it, or, at least, deprecate it after 1 or 2 release

**Comment by PhilippeAccorsi** [comment]
Whats going on when anonymised user ?
At present we replace (by default) public_name by `Lost Meerkat`. But what is going on with unique name ?

**Comment by raphj** [comment]
@lebouquetin Oh, right, it works for me too with Dolphin, I don't know what I did wrong the first time. It still feels a bit confusing to me though.

**Comment by PhilippeAccorsi** [comment]
We can create name by default with user_id like `suricate_{user_id}` and you can change that visible in frontend and save default name in database. Why it is necessary unique in frontend also ?

**Comment by lebouquetin** [comment]
@Skylsmoi @PhilippeAccorsi forcing the user to set a username is not only a migration process: this force him/her to decide how he/she will be mentionned. If we allow NULL username, the issue is the same. If we use LDAP, we can't force to have both email and username defined

**Comment by raphj** [comment]
Why would a NULL username be wrong? It seems it makes it easy to detect that a user should set their username on next login, contrary to a username set by default.

**Comment by lebouquetin** [comment]
> Why would a NULL username be wrong? It seems it makes it easy to detect that a user should set their username on next login, contrary to a username set by default.

@raphj see my point about multiple NULL value for a field defined as unique - https://github.com/tracim/tracim/issues/2829#issuecomment-617725844

**Comment by raphj** [comment]
@lebouquetin all right, we fully agree then :-)

**Comment by inkhey** [comment]
> > Standard SQL allow multiple null value with "Unique" field, so i don't see the problem.
> 
> I'm pretty sure it's not the case with all supported databases... I'd like you to try this, if its ok, so we can set NULL as default username, otherwise we set default value to `userxxx` with xxx being the `user_id`.

I tested with all supported database and all database have the same behaviour : considering each null as distinct values.

**Comment by inkhey** [comment]
about the unique, in sqlite doc: https://sqlite.org/faq.html#q26

> SQLite follows interpretation (1), as does PostgreSQL, MySQL, Oracle, and Firebird.

**Comment by lebouquetin** [comment]
> Whats going on when anonymised user ?
> At present we replace (by default) public_name by Lost Meerkat. But what is going on with unique name ?

We'll keep public name like in current version. For username I suggest we set it to NULL in this case

**Comment by PhilippeAccorsi** [comment]
> > Whats going on when anonymised user ?
> > At present we replace (by default) public_name by Lost Meerkat. But what is going on with unique name ?
> 
> We'll keep public name like in current version. For username I suggest we set it to NULL in this case

In this case (username is null) we show public_name or nothing ? If its nothing we can have toto like `"  " need your review`

**Comment by raphj** [comment]
I think we should always display the display name if not empty, with possibly the username in a title. We could also disallow todos and mentions for users who have not set their username.

**Comment by lebouquetin** [comment]
@PhilippeAccorsi 

- If Michel (@michel38) mentionned me, the comment is `@michel38 mentionned you in "Cahier des charges"`
- If he deletes his account, I suggest to show `someone mentionned youin "Cahier des charges"`

Note : notifications are not the right example because the must be independant from other entities

**Comment by lebouquetin** [comment]
After this entire discussion, I update the description of the issue.

**Comment by inkhey** [comment]
@lebouquetin  
need clarification about:
" allow to reset password from username"
How ?

**Comment by inkhey** [comment]
need clarifications about:

>  allow NULL value for email and username but never both being NULL at the same time

and:

>  anonymization process.

1. Check for not both null value should be done in database if possible if not in code.
2. Where are clear that anonymized user have not null email address but something like @anonymous ?

**Comment by inkhey** [comment]
"@" in username should probably be avoid:
- it cause unicity issue, if we need to be able to authenticate to 2 identity in the same time, user 1 should not have user 2 email as . We can resolve this issue using some kind of unicity but this simplify thing if someone want to know if email address is "…".
- It make mention harder to be done 

others characters may also be avoid depending on webdav support ?

**Comment by lebouquetin** [comment]
@inkhey what chars are allowed for username on services like github, twitter ?

Github rule: `Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen.`

This rule seems ok to me (something like `[azAZ0-9\-]`)

**Comment by inkhey** [comment]
About email and username conflict:
 | user_id | email                    | username            |
|---------|--------------------------|---------------------|
| 1       | user1@domainame.tld      | user1               |
| 2       | imahacker@domainname.tld | user1@domainame.tld |

In this case, if we get only one field to connect with both email or username, it's unclear which user should be authenticate

**Comment by lebouquetin** [comment]
@inkhey @Skylsmoi @metzgegu @gbonaspetti I updated the todo list and splitted it to distinguish frontend and backend stuff.

**Comment by gbonaspetti** [comment]
For each modification, besides the changes themselves, it is necessary to take care in the frontend with the translation. For the name of this feature (username) I talked to @celiamgtt and @metzgegu  and we thought about the translation, here are some ideas, but our opinion was to use the French translation _identifiant_ or _pseudo_:

English: 
- username
- nickname
- pseudo
- pseudonym

French: 
- identifiant
- nom d'utilisateur (easily confused with _Nom complet_)
- pseudo
- pseudonyme

Portuguese:
- nome do utilizador
- identificador (not much used)
- pseudónimo

Personally, I thought of using pseudonym/pseudonyme/pseudónimo to be coherent in all languages.
What do you think?

**Comment by lebouquetin** [comment]
@gbonaspetti 

I'm not happy with pseud which means `chat` / `forum`, not "serious game". In a context of work, pseudo is not the right word (not neutral like username)

- github.com ask for `username`
- gitlab.com ask for `username` and `full name`
- framapiaf in french ask for `identifiant`
- twitter ask for `nom et prénom` in french and build the `username` automatically. When you configure your account, you can setup `Ǹom` for your displayed name and `Nom d'utilisateur` for your username. BUT, the two are not on the same screen...

So I keep on suggesting to use `username` and `full name` ; maybe with an explanation and with a `@` prefix for username, eg :

![image](https://user-images.githubusercontent.com/907161/80191402-ef925000-8615-11ea-8161-6a39c58d1cbb.png)

**Comment by gbonaspetti** [comment]
@lebouquetin I understand and agree with your point. For the translation, don't you find _Nom complet_ and _Nom d'utilisateur_ confusing? Would it be better to go in the _username/identifiant/identificador_ direction?
Personally I think names without space are better for this feature.

**Comment by lebouquetin** [comment]
In French, `Nom d'utilisateur` is more explicit than `Identifiant`. I'm not fan of `Nom complet`, maybe `Nom visible` ou `Nom affiché`... mais je ne suis pas fan non plus.

Keep `Nom d'utilisateur` et `Nom complet`... I will ask for this on LinuxFR - we'll get lot's of answers, I think.

**Comment by gbonaspetti** [comment]
> In French, `Nom d'utilisateur` is more explicit than `Identifiant`. I'm not fan of `Nom complet`, maybe `Nom visible` ou `Nom affiché`... mais je ne suis pas fan non plus.
> 
> Keep `Nom d'utilisateur` et `Nom complet`... I will ask for this on LinuxFR - we'll get lot's of answers, I think.

Ok, thank you for your reply, I'm gonna add the translation to the issue description so it's consistent everywhere.

**Comment by lebouquetin** [comment]
Here comes the question on LinuxFR : https://linuxfr.org/forums/general-general

**Comment by lebouquetin** [comment]
By the way, I'd like we also add two extra fields to user profile:

- phone (optionnal, allow remote working groups to call each other - at least visible to administrators)
- company / organisation field (also at least visible to administrators)

Do you think we add these in the same development work @inkhey @gbonaspetti ? Or you'd prefer to add them through another issue?

**Comment by gbonaspetti** [comment]
> By the way, I'd like we also add two extra fields to user profile:
> 
> * phone (optionnal, allow remote working groups to call each other - at least visible to administrators)
> * company / organisation field (also at least visible to administrators)
> 
> Do you think we add these in the same development work @inkhey @gbonaspetti ? Or you'd prefer to add them through another issue?

In frontend is an easy development and will involve exactly the same changes as for username, for us it could be done in the same issue.

**Comment by inkhey** [comment]
> By the way, I'd like we also add two extra fields to user profile:
> 
>     * phone (optionnal, allow remote working groups to call each other - at least visible to administrators)
> 
>     * company / organisation field (also at least visible to administrators)
> 
> 
> Do you think we add these in the same development work @inkhey @gbonaspetti ? Or you'd prefer to add them through another issue?

We can, but we do need to be clear about implementation in database of these field. 
I suggest to have a json field for all these secondary informations related to user. It mean a bit more work in backend to see how to implement this well and performance will be worst but it also mean we can add easily information to user, especially for plugin/app.

**Comment by buxx** [comment]
After discussion with @gbonaspetti i added, for backend, `username can be modified` todo.

**Comment by lebouquetin** [comment]
> We can, but we do need to be clear about implementation in database of these field.
I suggest to have a json field for all these secondary informations related to user. It mean a bit more work in backend to see how to implement this well and performance will be worst than a normal field but it also mean we can add easily information to user, especially for plugin/app.

@inkhey this is a nice idea. Could you create an issue for this and I'll describe it (and we will move this for 3.x - this will answer all usecases I have been talked about)

**Comment by lebouquetin** [comment]
@gbonaspetti @metzgegu @Skylsmoi @buxx @inkhey 

About username and public_name, here is what we must implement:

- in API, keep `public_name` and add `username` fields
- in user interface
    - in English, keep `full name` and add `username`
    - in French, keep `Nom complet` and add `identifiant`

**Comment by buxx** [comment]
About `username` and `email` columns: 

> allow NULL value for email and username but never both being NULL at the same time

This will be implemented with `CHECK CONTRAINTS` and this is possible because Tracim only support MySQL > 8 and MariaDB > 10.3.

**Comment by buxx** [comment]
I opened this issue about first backend implementation: https://github.com/tracim/tracim/issues/2933

**Comment by PhilippeAccorsi** [comment]
One question: when we use tracim without email notification feature, we show a specifi message to the administrator about he need to inform user manually about his password.

If email is activated on Tracim, but admin not add email address, its necessary to show message about admin need to inform user manually. At present, all account have an email (existing email or email like toto@toto.toto), and if email notification is activated, administrator just see message about account created and user notified. Now we need to add a specific message.

**Comment by gbonaspetti** [comment]
> One question: when we use tracim without email notification feature, we show a specifi message to the administrator about he need to inform user manually about his password.
> 
> If email is activated on Tracim, but admin not add email address, its necessary to show message about admin need to inform user manually. At present, all account have an email (existing email or email like [toto@toto.toto](mailto:toto@toto.toto)), and if email notification is activated, administrator just see message about account created and user notified. Now we need to add a specific message.

I agree, I think we can add a warning flash message when the user is created if the email field is empty and the notifications are activated. What do you think?

**Comment by PhilippeAccorsi** [comment]
I think its a good solution :)

**Comment by gbonaspetti** [comment]
> I think its a good solution :)

Cool, I'm gonna update the corresponding issues

**Comment by lebouquetin** [comment]
As discussed this morning, we should have a configuration that refuse empty email. For example, Mon Tracim and any online instance should avoid empty email. This behavior should be the default (I think, a parameter like `allow_empty_password = False` in backend configuration file should be enough)

The interest of allowing empty email is for a local/internal use (like a school for example)

**Comment by gbonaspetti** [comment]
> > One question: when we use tracim without email notification feature, we show a specifi message to the administrator about he need to inform user manually about his password.
> > If email is activated on Tracim, but admin not add email address, its necessary to show message about admin need to inform user manually. At present, all account have an email (existing email or email like [toto@toto.toto](mailto:toto@toto.toto)), and if email notification is activated, administrator just see message about account created and user notified. Now we need to add a specific message.
> 
> I agree, I think we can add a warning flash message when the user is created if the email field is empty and the notifications are activated. What do you think?

After talking with @celiamgtt and @Skylsmoi we think it's best to place this message before the user's creation itself, then place the warning on the form, not a flash message.

**Comment by gbonaspetti** [comment]
> As discussed this morning, we should have a configuration that refuse empty email. For example, Mon Tracim and any online instance should avoid empty email. This behavior should be the default (I think, a parameter like `allow_empty_password = False` in backend configuration file should be enough)
> 
> The interest of allowing empty email is for a local/internal use (like a school for example)

Ok, I will update this in the issue description too, just to confirm the only impact on the interface would be on the forms not allowing the null field if this parameter is deactivated (and the warnings/errors related to this)? 
If the parameter was activated, a user was created with null e-mail and the parameter was deactivated, should we do any special treatment?

**Comment by lebouquetin** [comment]
@gbonaspetti I think nothing to do on frontend except manage error returned by the backend

**Comment by lebouquetin** [comment]
And no special treatment if backend conf changes: this is a case to be managed by the adminsys
