### ISSUE TITLE
Feat: Implement Open-Graph meta in content pages

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3453]
## Feature description and goals

[OpenGraph](https://ogp.me/) is a common way to describe a web page and provide metadata about it. It has been created to ease displaying the preview (text/image) of contents in external services.
Adding those data in Tracim content pages (`https://algoo.tracim.fr/ui/workspaces/94/contents/file/14573`/...) would allow the contents to have a preview in other services like Mattermost.

- [ ] Verify how the retrieving of this data is handled
- [ ] Generate the 4 required metadata (`title`, `type`, `image`, `url`) for those pages. The image can use the website logo (or the preview in case of images/videos?)
- [ ] Generate the `description` meta for text-based contents (office documents/pdf/…).

## Prerequisites

- Have we access to a textual preview of contents?

**Comment by grignards** [comment]
From what I saw mattermost does the queries through their backend.
