### ISSUE TITLE
Feat: Manage user membership for spaces of type ON_REQUEST

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3539]
## Feature description and goals

Having spaces which are visible by every user, but where access is restricted by the space managers is useful to add "discoverability" to Tracim. This access type will be implemented by the `ON_REQUEST` spaces.
The user will be able to ask for membership (this action is named *workspace subscription*). This subscription can be accepted or rejected by any of the space managers/administrators. The subscription's state can have three values:  `PENDING`, `ACCEPTED` or `REJECTED`.

### Database layout

- [x] A workspace subscription (as stored in the database) will have the following structure:
```python
class WorkspaceSubscription:
  # current state of the subscription
  state: SubscriptionStateEnum
  # datetime where the subscription was created
  created_date": datetime
  # id of the workspace the subscription is for
  workspace_id: int
  # id of the user the subscription has been created by
  author_id: int
  # datetime where the subscription was accepted/rejected
  evaluation_date: Optional[datetime] = None
  # id of the user who accepted/rejected the subscription
  evaluator: Optional[int] = None
```
- [x] the subscription's primary key will be (workspace_id, author_id).
- [ ] as accepting a subscription deletes it (see below), add a check that a subscription's is never `ACCEPTED` in the database. :warning: not implemented see issue #3662

### Add an API GET `/api/users/<user_id>/workspace_subscriptions`

- [x] accessible by the current user and administrators
- [x] which will return the list of subscriptions of the given user as objects of type:
```json
{
  "state": "PENDING",
  "created_date": "2020-08-27",
  "workspace": {"workspace_id": 42, "label": "Space", "slug": "space"},
  "author": {"public_name": "A user", "user_id": 23, "username": "user"},
  "evaluation_date": null,
  "evaluator": null
}
```

### Add an API PUT `/api/users/<user_id>/workspace_subscriptions`

- [x] accessible by the current user and administrators
- [x] accepts an object of type:
```json
{
  "workspace_id": 42,
}
```
- [x] only accepts ids of `ON_REQUEST` spaces, returns a 400 http code + specific error code (`INVALID_WORKSPACE_ACCESS_TYPE`?)if not.
- [x] if no subscription exists for the (user_id,workspace_id) pair: creates a user subscription and set its state to `PENDING` 
- [x] if a subscription exists for the (user_id,workspace_id) pair: set the subscription state to `PENDING` and reset evaluator date/id.
- [x] returns the created/updated subscription as would the GET API.

N.B.: I chose the `PUT` http medoth as the behavior is an "upsert" which does not directly map on a classic method. `PUST` would be useful for this :-)

### Add an API GET `/api/workspaces/<workspace_id>/subscriptions`

- [x] will return all subscriptions for the given workspace
- [x] accessible by the given workspace managers and administrators only 
- [x] returned objects will have type:
```json
{
  "state": "PENDING",
  "created_date": "2020-08-27",
  "evaluation_date": "2020-08-29",
  "workspace": {"workspace_id": 42, "label": "Space", "slug": "space"},
  "author": {"public_name": "A user", "user_id": 23, "username": "user"},
  "evaluator": {"user_id": 1, "public_name": "Admin", "username": "TheAdmin"}
}
```

### Add an API PUT `/api/workspaces/<workspace_id>/subscriptions/<user_id>/accept`

- [x] accessible by the given workspace managers and administrators only 
- [x] accepts input of type:
```json
{
  "role": "reader"
}
```

- [ ] returns a 400 error if the subscription's state is not `PENDING`, error code `INVALID_SUBSCRIPTION_STATE`? . Not implemented as this doesn't make much sense: https://github.com/tracim/tracim/issues/3539#issuecomment-701287012
- [x] sets the `evaluation_date` to `utcnow()` and the `evaluator_id` to the current user.
- [x] adds the subscription's author in the space with the given role.
- [ ] deletes the subscription : :warning:  not implemented see issue #3662 
- [x] returns an empty body, 204 code

### Add an API PUT `/api/workspaces/<workspace_id>/subscriptions/<user_id>/reject`

- [x] accessible by the given workspace managers and administrators only
- [x] no body input
- [x] sets the `evaluation_date` to `utcnow()` and the `evaluator_id` to the current user.
- [x] returns an empty body, 204 code

### Events and TLMs

- [x] Generate events and TLMs for the author, space managers and administrators when a subscription is created and changes state.
- The TLM shall include a `workspace_subscription` field as returned by the APIs, a `workspace` field (as other TLMs related to a workspace and an `author` field (as all TLMs).
- The TLM type will be workspace_subscription.(created|modified).

## Prerequisites

- #3536
- #3540 (update of workspace digest schema)

### Can the ON_REQUEST access type be disabled (by configuration)?

**Decision**: Yes, see #3602

### Should the subscribing user automatically be added by the backend when state becomes ACCEPTED?

This also could be done by the frontend (call to PO`INVALID_WORKSPACE_ACCESS_TYPE`ST workspace/members) but could lead to inconsistency if a subscription is accepted then the member never added because of a bug or error (network failure for instance).

It could also be useful to store the role the member gets when his subscription is added for history purposes.

**Decision** : the user will automatically be added as member with the given role, we won't keep an history of accepted subscriptions: when a subscription is accepted it is deleted.

## Implemented solution

- add workspace_subscription table + migration scripts
- Add endpoint to deal with on_request subscription of workspaces:
  - Add an API GET /api/users/<user_id>/workspace_subscriptions
  - Add an API PUT /api/users/<user_id>/workspace_subscriptions
  - Add an API GET /api/workspaces/<workspace_id>/subscriptions
  - Add an API PUT /api/workspaces/<workspace_id>/subscriptions/<user_id>/accept
  - Add an API PUT /api/workspaces/<workspace_id>/subscriptions/<user_id>/reject
- Add TLM for workspace_subscription
- This implementation does not drop any subscription and do store evaluator and evaluation date.

**Comment by inkhey** [comment]
- PUT `/api/workspaces/<workspace_id>/user_subscriptions/<subscription_id>/state` should be accessible by workspace managers and administrators only , i am right ?
- Are we sure we want the word "subscription" be associated to "space subscription" in backend code ? The proposal doesn't make easy to understand the subscription mecanism if we do want for exemple to "subscribe" to notification of a specific document (just an exemple) .

**Comment by grignards** [comment]
> Just some remarks :
> 
>     * PUT `/api/workspaces/<workspace_id>/user_subscriptions/<subscription_id>/state` should be accessible by workspace managers and administrators only , i am right ?

Yes, I'll add this precision

>     * Are we sure we want the word "subscription" be associated to "space subscription" in backend code ? The proposal doesn't make easy to understand the subscription mecanism if we do want for exemple to "subscribe" to notification of a specific document (just an exemple) .

I can understand, subscription is rather general… would "workspace_subscriptions" be OK (using the user POV) ?

**Comment by inkhey** [comment]
workspace_subscriptions is ok for me.

**Comment by inkhey** [comment]
An API suggestion:
for `/api/users/<user_id>/workspace_subscriptions`, i do suggest either:
-POST  `/api/users/<user_id>/workspace_subscriptions` accepting a list of workspace id instead of only one (more powerful)
- if we do really want to be specific to one workspace (i'm not sure that's better, i do prefer  POST`/api/users/<user_id>/workspace/<workspace_id>/subscribe`

**Comment by inkhey** [comment]
> An API suggestion:
> for POST `/api/users/<user_id>/workspace_subscriptions`, i do suggest either:
> 
>     * POST  `/api/users/<user_id>/workspace_subscriptions` accepting a list of workspace id instead of only one (more powerful), do return 204.
> 
>     * if we do really want to be specific to one workspace (i'm not sure that's better), i do prefer  POST`/api/users/<user_id>/workspaces/<workspace_id>/subscribe`
> 
> 
> note: the list make sense because we do have only one parameter to put: workspace id.

Note: as we do later may maybe want to add a text associated to the request. current api make more sense, is there any discussion about this kind of mecanism ?

**Comment by inkhey** [comment]
This last point let me think about the fact that we:
- should probably do not allow having multiple "active" (multiple PENDING) request to a same space.
- but should have a specific error code for this case in order to tel frontend "you have already request to go into this space".

What should also be the behavior of leaving a space where user does have subscriptions on it ? What happened to subscription as soon as user get into the space ?

**Comment by grignards** [comment]
> This last point let me think about the fact that we:
> 
>     * should probably do not allow having multiple "active" (multiple PENDING) request to a same space.

You're right, I'll add this to the tasks list.

>     * but should have a specific error code for this case in order to tel frontend "you have already request to go into this space".
> 
> 
> What should also be the behavior of leaving a space where user does have subscriptions on it ? What happened to subscription as soon as user get into the space ?

In general a user shouldn't be able to leave a space where a subscription has not been accepted as he is not member of it. We could have this case if the user has a subscription but then is added to the space directly (without accepting the subscription).
We could handle this by accepting the existing subscription (if there is one) when a user is added to a space. Then we wouldn't need the PUT `.../state` API.

> should we allow a user to resubscribe to a space ?

Yes, as long as he has no active subscription for it. Later on we could think of a way to avoid spamming space managers with repeated requests.

**Comment by inkhey** [comment]
> ### Should the subscribing user automatically be added by the backend when state becomes ACCEPTED?
> 
> This also could be done by the frontend (call to POST workspace/members) but could lead to inconsistency if a subscription is accepted then the member never added because of a bug or error (network failure for instance).
> 
> It could also be useful to store the role the member gets when his subscription is added for history purposes.

I see two different meaning for subscribe mecanism:

- space subscription is unique to space and user (primary key) and is independant from membership. It allow just to be able to be member of space. If user does leave space, the subscription is always true and user can get into the space without any trouble. The drawback is with this system, it's more complicated to deal with "multiple request" if we do later want a request to be associated to text or some other data to explain you should be allowed to come in.

- an user can create multiple subscription to same space but not at the same time. as soon as user get into a space, the previous accepted subscription is disabled. we can't get multiple pending subscription, but user can resend request to get into if his previous one was not accepted. This behavior seems more straightforward if we do want to associated some data to the subscription. in this case it make sense to automatically add user to space and disable accepted subscription at same time. if user leave a space, he has to remake a request.

**Comment by grignards** [comment]
> An API suggestion:
> for POST `/api/users/<user_id>/workspace_subscriptions`, i do suggest either:
> 
>     * POST  `/api/users/<user_id>/workspace_subscriptions` accepting a list of workspace id instead of only one (more powerful), do return 204.

In general for RESTful APIs posting to a collection creates only one new resource and here we shouldn't get that many subscriptions in one batch (even if the user interface allows to make a request relatively quickly) so I do not see a real advantage to take a list.

>     * if we do really want to be specific to one workspace (i'm not sure that's better), i do prefer  POST`/api/users/<user_id>/workspaces/<workspace_id>/subscribe`

This one does not make sense to me as the `/api/users/<user_id>/workspaces/<workspace_id>` resource does not exist when the user wants to subscribe to a space. The semantic (that is kept) is `workspaces` lists the spaces the user is member of.

> note: the list make sense because we do have only one parameter to put: workspace id.

**Comment by grignards** [comment]
> Note: as we do later may maybe want to add a text associated to the request. current api proposal make more sense, is there any discussion about this kind of mecanism ?

It has been discussed, we won't do it now but it could arrive later on.

**Comment by grignards** [comment]
> I see two different meaning for subscribe mecanism:
> 
>     * space subscription is unique to space and user (primary key) and is independant from membership. It allow just to be able to be member of space. If user does leave space, the subscription is always true and user can get into the space without any trouble. The drawback is with this system, it's more complicated to deal with "multiple request" if we do later want a request to be associated to text or some other data to explain you should be allowed to come in. **In this case automatically add user doesn't seems really useful, but can be made**.
> 
>     * an user can create multiple subscription to same space but not at the same time. as soon as user get into a space, the previous accepted subscription is disabled. we can't get multiple pending subscription, but user can resend request to get into if his previous one was not accepted. This behavior seems more straightforward if we do want to associated some data to the subscription. **in this case it make sense to automatically add user to space** and disable accepted subscription at same time. if user leave a space, he has to remake a request.

What has been defined for now is more the second behavior you describe: a user has access to his history of subscriptions, and he can make several subscriptions for a space (which are kept separated) as long as two are not active at the same time.

**Comment by inkhey** [comment]
> > Note: as we do later may maybe want to add a text associated to the request. current api proposal make more sense, is there any discussion about this kind of mecanism ?
> 
> It has been discussed, we won't do it now but it could arrive later on.

If so, i'm ok with  `POST /api/users/<user_id>/workspace_subscriptions`, i just don't like the idea of pushing id only to endpoint, but if we do imagine pushing other data, that's different.

**Comment by inkhey** [comment]
> > I see two different meaning for subscribe mecanism:
> > ```
> > * space subscription is unique to space and user (primary key) and is independant from membership. It allow just to be able to be member of space. If user does leave space, the subscription is always true and user can get into the space without any trouble. The drawback is with this system, it's more complicated to deal with "multiple request" if we do later want a request to be associated to text or some other data to explain you should be allowed to come in. **In this case automatically add user doesn't seems really useful, but can be made**.
> > 
> > * an user can create multiple subscription to same space but not at the same time. as soon as user get into a space, the previous accepted subscription is disabled. we can't get multiple pending subscription, but user can resend request to get into if his previous one was not accepted. This behavior seems more straightforward if we do want to associated some data to the subscription. **in this case it make sense to automatically add user to space** and disable accepted subscription at same time. if user leave a space, he has to remake a request.
> > ```
> 
> What has been defined for now is more the second behavior you describe: a user has access to his history of subscriptions, and he can make several subscriptions for a space (which are kept separated) as long as two are not active at the same time.
> And the space subscriptions available to managers keep track of all subscriptions made.

To distinct active or inactive one, we can either:
- Get the last one (by id or date): don't need specific code but less clear when reading the database
- Add a active/inactive boolean field int the WorkspaceSubscription table.

Also, we should clarify if subscription is valid after user get out of workspace. If we decide the subscription last longer it will make thing complicated as there is the case the user remove itself where it make sense to keep subscription, but the case where admin removed it is different, admin most probably don't want user to reget into the workspace. So i suggest subscription lifetime end directly after user get into a space, and creating a new subscription disable the older one.

**Comment by raphj** [comment]
> Can the ON_REQUEST access type be disabled (by configuration)?

Let's wait for a use case / demand for this, no?

**Comment by raphj** [comment]
> Should the subscribing user automatically be added by the backend when state becomes ACCEPTED?

I'd say yes, to make the workflow as simple as possible. And then refine if we need something more complicated in the future.

**Comment by grignards** [comment]
> To distinct active subscription, we can either:
> 
>     * Get the last one (by id or date): don't need specific code but less clear when reading the database(1)
> 
>     * Add a active/inactive boolean field int the WorkspaceSubscription table.

err… for me an active subscription is one that has the `PENDING` state.

> 
> Also, we should clarify if subscription is valid after user get out of workspace. If we decide the subscription last longer it will make thing complicated as there is the case the user remove itself where it make sense to keep subscription, but the case where admin removed it is different, admin most probably don't want user to reget into the workspace. So i suggest subscription validity lifetime end directly after user get into a space, and creating a new subscription disable the older one.

What do you mean by "valid"? Did you see [my answer to your previous comment](#issuecomment-693248833)?

>     * (1) if we decide lifetime is short we should also don't get subscription for workspace you're in.

**Comment by inkhey** [comment]
> > To distinct active subscription, we can either:
> > ```
> > * Get the last one (by id or date): don't need specific code but less clear when reading the database(1)
> > 
> > * Add a active/inactive boolean field int the WorkspaceSubscription table.
> > ```
>  
> err… for me an active subscription is one that has the `PENDING` state.

In my mind, active mean "the current subscription" state, it can been cancelled, pending or accepted. If for some reason we do historically have accepted user in the space but then removed it and then he redo a request, we probably do want to keep the historic but do need to know what is the current state. An accepted subscription should not last forever if we do want to remove user, so we do need to distinctly know which subscription is the current one for user/workspace and which are older one.

> 
> > Also, we should clarify if subscription is valid after user get out of workspace. If we decide the subscription last longer it will make thing complicated as there is the case the user remove itself where it make sense to keep subscription, but the case where admin removed it is different, admin most probably don't want user to reget into the workspace. So i suggest subscription validity lifetime end directly after user get into a space, and creating a new subscription disable the older one.
> 
> What do you mean by "valid"? Did you see [my answer to your previous comment](#issuecomment-693248833)?
> 
> > ```
> > * (1) if we decide lifetime is short we should also don't get subscription for workspace you're in.
> > ```

I do read it but it seems we do not think or the same case. I do think about the case a user leave a workspace and have accepted subscription. What should be the meaning of this ?

**Comment by lebouquetin** [comment]
- interesting : add a now() datetime when adding a membership
- history of requests: can be found through TLM
- request + membership :+1: 
   - validating/refusing a request is one API action (the backend encapsulate membership creation / request processing)
- request is deleted when it is accepted
- request is not deleted when it is refused
- validating/refusing a request will be done through a logical API: `PUT workspaces/id/subscriptions`

**Comment by inkhey** [comment]
> ### Add an API PUT `/api/users/<user_id>/workspace_subscriptions`
> 
>     * [ ]  accessible by the current user and administrators
> 
>     * [ ]  accepts an object of type:
> 
> 
> ```json
> {
>   "workspace_id": 42,
> }
> ```
> 
>     * [ ]  only accepts ids of `ON_REQUEST` spaces, returns a 400 http code if not.
> 
>     * [ ]  if no subscription exists for the (user_id,workspace_id) pair: creates a user subscription and set its state to `PENDING`
> 
>     * [ ]  if a subscription exists for the (user_id,workspace_id) pair: set the subscription state to `PENDING` and reset evaluator date/id.
> 
>     * [ ]  returns the created/updated subscription as would the GET API.
> 

Need clarification now or after fixing in this issue about the error_code if not "IN REQUEST" workspace.


> ### Add an API PUT `/api/workspaces/<workspace_id>/subscriptions/<user_id>/accept`
> 
>     * [ ]  accessible by the given workspace managers and administrators only
> 
>     * [ ]  accepts input of type:
> 
> 
> ```json
> {
>   "role": "reader"
> }
> ```
> 
>     * [ ]  returns a 400 error if the subscription's state is not `PENDING`
> 
>     * [ ]  sets the `evaluation_date` to `utcnow()` and the `evaluator_id` to the current user.
> 
>     * [ ]  adds the subscription's author in the space with the given role.
> 
>     * [ ]  deletes the subscription
> 
>     * [ ]  returns an empty body, 204 code
> 

Need clarification now or after fixing in this issue about the error_code if not "PENDING" workspace.


> ### Add an API PUT `/api/workspaces/<workspace_id>/subscriptions/<user_id>/reject`
> 
>     * [ ]  accessible by the given workspace managers and administrators only
> 
>     * [ ]  no body input
> 
>     * [ ]  sets the `evaluation_date` to `utcnow()` and the `evaluator_id` to the current user.
> 
>     * [ ]  returns an empty body, 204 code
> 

Need clarification now or after fixing in this issue about the behavior if not "PENDING" workspace, i do think the behavior should be same as for accept, no ? If really we do want to be able to accept a "refused" user, it should probably be a standard invitation, not changing the status of an old subscription, no ? This way the subscription mecanism does work only in one way:

```
PENDING ---OR --> VALIDATED -> item automatically deleted
           |
           \-> REFUSED
```

**Comment by grignards** [comment]
> Need clarification now or after fixing in this issue about the behavior if not "PENDING" workspace, i do think the behavior should be same as for accept, no ? If really we do want to be able to accept a "refused" user, it should probably be a standard invitation, not changing the status of an old subscription, no ? This way the subscription mecanism does work only in one way:
> 
> ```
> 
> ```

Yes this was a bad copy/paste. Allowing the change from REJECTED -> ACCEPTED would mean that managers can have a change of mind/allow error though… So it may not be a bad idea.

So that we get this state machine:

PENDING ---OR --> VALIDATED -> item automatically deleted
           |                       Î
           \------> REFUSED

**Comment by grignards** [comment]
I'm gonna leave the possibility to accept a subscription after rejecting it because I do not see an adverse effect in doing so.
I added the required error codes (not the numbers but their name).

**Comment by inkhey** [comment]
Some change between current state implementation (https://github.com/tracim/tracim/pull/3656) and spec (no including unimplemented feature):
- Using `UserDigestSchema` for author and evaluator of workspace_subscription with contain also avatar_url (not specified here),  not really an issue but i prefer to mention it.
- Using `WorkspaceDigestSchema` for workspace. waiting for merging #3540 to get a real digest version
- storing `evaluator_id` instead of `evaluator`, `evaluator` is the user object, `evaluator_id` the `user_id`, like for `author`.

**Comment by inkhey** [comment]
One point is still unclear for me, what should be the behavior with` accepting = deletion` here:

It doesn't make sense to set evaluator and evaluation_date if we do accept, if in this case we do drop the subscription at the same time, unless we do find a solution to make 2 consequent change and return 2 different TLM for theses informations .

so, i do see multiple approach:
1. we do only delete the subscription.
2. verify if possible with sqlachemy to get trigger without commiting ? (i need to take some time to getter understood the current sqlalchemy trigger code)
3. sqlalchemy "trigger" that automatically remove accepted subscription.

The last one seems to me the cleanest as it mean we can have explicit tlm with evaluator info for validated subscription too.

**Comment by inkhey** [comment]
> I'm gonna leave the possibility to accept a subscription after rejecting it because I do not see an adverse effect in doing so.
> I added the required error codes (not the numbers but their name).

Du to the acceptance of such rule `INVALID_SUBSCRIPTION_STATE` error codes does not make much sense now.

**Comment by lebouquetin** [comment]
@inkhey I do not understand what you mean by accepting = deletion

> sqlalchemy "trigger" that automatically remove accepted subscription.

This is magic - complicated to understand and to maintain.

**Comment by inkhey** [comment]
> @inkhey I do not understand what you mean by accepting = deletion

We have previously decided that accepting a subscription meaning deleting it: 
> as accepting a subscription deletes it (see below), add a check that a subscription's is never ACCEPTED in the database.

But we do have incoherent specification with this:
> sets the evaluation_date to utcnow() and the evaluator_id to the current user.

if acceptation delete the subscription, the information about evaluator and evaluation_date will not be saved.

**Comment by inkhey** [comment]
After checking source code and discussion with @raphj, i see 3 solutions:
- We do drop the accepted subscription and we do not store both evaluator and evaluation_date. We do have this information by TLM. This can be an problem depending on what the frontend want to present for acceptation or rejection of subscription.
- We do drop the accepted subscription and we do store both evaluator and evaluation_date. We do have this information by TLM. This can be an problem depending on what the frontend want to present for acception of subscription
- We just do not drop the accepted subscription. Subscription stay visible at `accepted` status after acceptation. If user decide to leave space, it's not required to drop this accepted subscription. User can just make a new subscription which will reset the status to `pending`. This make behavior a bit less obvious because client has to take into account that have an accepted subscription for a space doesn't mean being accepted into. If user is both outside and with an accepted subscription for a space, this mean either:
  - that user has been previously accepted in the space.
  - a bug.

**Comment by raphj** [comment]
Instead of solutions, I see one question, for @celiamgtt:

Should we show the time / date at which a request to join a space was accepted or refused?

If so, we need to keep the information in the database and we should probably not remove the subscription when it is accepted. TLMs are not enough: they are difficult to query.

**Comment by celiamgtt** [comment]
@raphj Showing the time / date information is always (most of the time) a good idea, but I would say if it's too complicated it's not mandatory. But I see other problems if we don't keep the time / date: how to manage the users who are spamming their demands? It could also be interesting for the next features: for example if later we want to have a latest members section.

**Comment by raphj** [comment]
Okay, so I'd say let's keep the entry for now, it seems even simpler than trying to delete it on accept, even if we don't use the information for now.

**Comment by celiamgtt** [comment]
@inkhey Told me that it could display the members name even in a rejection case? That could be a problem.

**Comment by raphj** [comment]
we should not do that indeed, but what makes you think this @inkhey?  This seems out of the scope of this issue?

**Comment by inkhey** [comment]
> we should not do that indeed, but what makes you think this @inkhey? This seems out of the scope of this issue?

- we do return `evaluator` in `GET /api/users/<user_id>/workspaces_subscriptions`. 
  - solution : remove evaluator from subscription
  - drawback: we loss information for administrator who want to know which administrator has done this change
- we do leak the author of a invalidation in TLM .
  - workaround: set author to None
  - drawback: we love the evaluator information.

**Comment by inkhey** [comment]
> > we should not do that indeed, but what makes you think this @inkhey? This seems out of the scope of this issue?
> 
>     * we do return `evaluator` in `GET /api/users/<user_id>/workspaces_subscriptions`.
>       
>       * solution : remove evaluator from subscription
>       * drawback: we loss information for administrator who want to know which administrator has done this change
> 
>     * we do leak the author of a invalidation in TLM .
>       
>       * workaround: set tlm author to None
>       * drawback: we lost the evaluator information in tlm

If we do not have the TLM mecanism, we may use different schema to release more or less information but TLM are unique for one event which is received by person outside and inside of the space, so i don't see simple solution.

**Comment by lebouquetin** [comment]
I think you are over-engineering stuff. Leak the evaluator name for now.

**Comment by inkhey** [comment]
Current issue implementation : 
https://github.com/tracim/tracim/pull/3656
- Do not remove accepted subscriptions
- Do keep both evaluation_date and evaluator .

@raphj i do suggest to create an issue to clarify these last point and merge the current code state.
I also suggest to rollback https://github.com/tracim/tracim/pull/3656/commits/a836a79affe15d82983d33528d1e15b730192394 fix from this branch and create a specific issue about these problem i had with transaction when debugging this. This fix may also been backported to 3.1.x , if needed.

**Comment by inkhey** [comment]
> Current issue implementation :
> #3656
> 
>     * Do not remove accepted subscriptions.
> 
>     * Do keep both evaluation_date and evaluator.
> 
> 
> @raphj i do suggest to create an issue to clarify theses last points and review/merge the current code state (i don't see any real problem with current implementation, despite it's probably not the cleanest one).
> I also suggest to rollback [a836a79](https://github.com/tracim/tracim/commit/a836a79affe15d82983d33528d1e15b730192394) fix from this branch and create a specific issue about these problem i had with transaction when debugging this. This fix may also been backported to 3.1.x , if needed.

After discussion with @raphj  and @Skylsmoi , we decide for a first iteration to : 
- remove `evaluator` from `SubscriptionSchema`, making evaluator not visible from API
- set author to empty for all `workspace_subscription` TLM.

A ticket will be created to clarify the unclear points:
- Should we make `evaluator` visible in endpoint `/api/workspaces/<workspace_id>/subscriptions` only visible by workspace manager and administrator ? (meaning both creating a second schema for subscription and adapt frontend if we do want to update this information, as it will not be updated automatically through TLM)
- Should subscription been deleted after validation ? (as we do not store the evaluator in ui, it make sense to keep them to keep trace.

**Comment by inkhey** [comment]
> > Current issue implementation :
> > #3656
> > ```
> > * Do not remove accepted subscriptions.
> > 
> > * Do keep both evaluation_date and evaluator.
> > ```
> > 
> > 
> > @raphj i do suggest to create an issue to clarify theses last points and review/merge the current code state (i don't see any real problem with current implementation, despite it's probably not the cleanest one).
> > I also suggest to rollback [a836a79](https://github.com/tracim/tracim/commit/a836a79affe15d82983d33528d1e15b730192394) fix from this branch and create a specific issue about these problem i had with transaction when debugging this. This fix may also been backported to 3.1.x , if needed.
> 
> After discussion with @raphj and @Skylsmoi , we decide for a first iteration to :
> 
>     * remove `evaluator` from `SubscriptionSchema`, making evaluator not visible from API
> 
>     * set `author` to empty for all `workspace_subscription` TLM.
> 
> 
> A ticket will be created to clarify the unclear points:
> 
>     * Should we make `evaluator` visible in endpoint `/api/workspaces/<workspace_id>/subscriptions` only visible by workspace manager and administrator ? (meaning both creating a second schema for subscription and adapt frontend if we do want to update this information, as it will not be updated automatically through TLM)
> 
>     * Should subscription been deleted after validation ? (as we do not store the evaluator in ui, it make sense to keep them to keep trace.

After rediscussion with @lebouquetin , we will review and merge first the current implementation and then in another ticket we will adapt the behavior.

**Comment by inkhey** [comment]
ticket about solving the remaining unclear point here : https://github.com/tracim/tracim/issues/3662

**Comment by PhilippeAccorsi** [comment]
@inkhey this issue need some more comment about uncheck box in description. What is done, what is not done and why. also missing information about test here. If no test are necessary, please add some comment about that.
Thanks in advance.

**Comment by inkhey** [comment]
> @inkhey this issue need some more comment about uncheck box in description. What is done, what is not done and why. also missing information about test here. If no test are necessary, please add some comment about that.
> Thanks in advance.

I added explanation about each point unchecked in the issue.
For test, no manual test is required and was done (the PR was merged), see PR comment here: https://github.com/tracim/tracim/pull/3663#issuecomment-702705072

**Comment by PhilippeAccorsi** [comment]
Thanks.
Done.
