### ISSUE TITLE
Feat: Add link between users (follow)

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3916]
## Feature description and goals

- [x] Users should be able to follow each other (see #3910).
- [x] It should be possible to see how many people a user follows and how many people follow this user (see #3915).
- [x] It should be possible to recover the following status of two users (see #3909).

## Implementation

- [x] a new table `user_followers` with 3 columns:
  - `follower_id` which will contain the "follower"'s user id
  - `leader_id` which will contain the "leader"'s user id
  - `created_date` which will contain the datetime of the relationship creation.
  - UNIQUE/PRIMARY KEY constraint on `(follower_id, leader_id)`
- [x] a `/users/<user_id>/following` endpoint with:
  - POST `{"user_id": "<user_id_2>"}`: adds a `(user_id, user_id_2)`row in the `user_relationship`. If already present, return a 400 + error code
  - GET returning all list of `[{"user_id": "<user_id>", …}]` with an optional `user_id` parameter to filter + pagination (as in `messages` API)
  - DEL `/users/<user_id>/following/<user_id_2>`: removes the row `(user_id, user_id_2)` from the `user_relationship` table
Only accessible by when the logged user is <user_id> or is an administrator
- [x] a `/users/<user_id>/followers` with:
  - GET returning the list of followers `["user_id" : "<user_id>", …]`, with an optional `user_id` parameter to filter  + pagination (as in `messages` API)
Only accessible by when the logged user is <user_id> or is an administrator
- [x] a migration script to create the new table
- [x] Add `/api/users/{user_id:\d+}/public_profile` endpoint returning `{"followers_count": 42, "following_count": 42}` accessible by any connected user

## Notes

The third endpoint is to avoid leaking link information to unrelated users, if we do not care about this it could be removed and instead allow access to `/users/<user_id>/followers` by anybody.

## References

- https://inviqa.com/blog/storing-graphs-database-sql-meets-social-network

**Comment by inkhey** [comment]
Does we expect 
`GET /users/<user_id>/following`
and 
`GET /users/<user_id>/followers`
to be paginated by default ?

It's not so hard to do so, and it's future proof, so i suggest to think about it more frequently.

**Comment by inkhey** [comment]
> 
>     from_id which will contain the "follower"'s user id
>     to_id which will contain the "leader"'s user id

Wasn't better to rename from_id to follower_id and to_id to leader_id ? Does we expect this table to be used for other relationship than following ?  If yes, we should probably make a better documentation in code (and maybe in database itself) to make this more explicit: https://github.com/tracim/tracim/issues/2740

**Comment by grignards** [comment]
It's not so hard to do so, and it's future proof, so i suggest to think about it more frequently.

Yes we can add pagination here, I didn't put it explicitly as I think we still have a long way before a list of user ids becomes huge (not like a list of contents/messages/…).

**Comment by grignards** [comment]
> Wasn't better to rename from_id to follower_id and to_id to leader_id ? Does we expect this table to be used for other relationship than following ? If yes, we should probably make a better documentation in code (and maybe in database itself #2740) to make this more explicit:

Potentially the table could be used for any type of relationship, but I wonder if I'm not seeing too far here. Maybe `user_followers` with `(leader_id, follower_id, creation_date)` is enough for now. I'll change the namings.

**Comment by inkhey** [comment]
I have some suggestion for a consistent api, this consist of applying similar principle as existing endpoint, we may decide to do differently, but this may signify that we should change existing api if we want to be consistent.

- rename GET `/users/<user_id>/followers_count` to GET ` /users/<user_id>/followers/summary` which will return all global information we decide to be useful for followers. Idea is to have similar syntax as for` /api/users/{user_id:\d+}/messages/summary` and `/api/users/{user_id:\d+}/messages` . I do suggest something like this as return : 
```
{
  "followers_count": 42,
  "user": {
    "avatar_url": "/api/asset/avatars/john-doe.jpg",
    "public_name": "John Doe",
    "user_id": 3,
    "username": "My-Power_User99"
  },
  "user_id": 3
}
```
- add `GET /users/<user_id>/following/summary` endpoint:
```
{
  "following_count": 42,
  "user": {
    "avatar_url": "/api/asset/avatars/john-doe.jpg",
    "public_name": "John Doe",
    "user_id": 3,
    "username": "My-Power_User99"
  },
  "user_id": 3
}
```

- make `/users/<user_id>/following and /users/<user_id>/follower` returned offset free paginated result as `/api/users/{user_id:\d+}/messages` example.

**Comment by grignards** [comment]
Renaming `/api/users/<user_id>/followers_count `to `/api/users/<user_id>/followers/summary` is ok for me, I'm not too fond of it as it breaks the collection semantics (`/api/users/<user_id>/followers/summary` would usually mean "Get the follower of id 'summary'") but as it is used in other places we can do that.
Paginating the apis is fine **only** if we give a `total_count` in the results as getting the followers list is currently useful to display the number of followers of a user.

**Comment by inkhey** [comment]
> Paginating the apis is fine **only** if we give a `total_count` in the results as getting the followers list is currently useful to display the number of followers of a user.

I'm not sure to understood this point.

**Comment by raphj** [comment]
total_count should have the count of all the followers / following users, and not the number returned in this result set

**Comment by grignards** [comment]
My bad… we have the `summary` endpoint for this so we do not need `total_count`.

**Comment by grignards** [comment]
An alternative to those two `summary` endpoints would be to have `/api/users/<user_id>/relationship_summary` returning
```json
{
  followers_count: 42,
  following_count: 23
}
````

**Comment by buxx** [comment]
@gbonaspetti A security question. As I read:

* GET `/users/<user_id>/following` is accessible by any connected user
* GET `/users/<user_id>/followers` is accessible by when the logged user is <user_id> or is an administrator

Am I correct ?

About:

> The third endpoint is to avoid leaking link information to unrelated users, if we do not care about this it could be removed and instead allow access to /users/<user_id>/followers by anybody.

Which endpoint are you talking about ?

**Comment by raphj** [comment]
> Am I correct?

I would keep GET /users/<user_id>/following only accessible to the logged user and administrators


> Which endpoint are you talking about ?

/users/<user_id>/following/summary I think

**Comment by raphj** [comment]
I would go for https://github.com/tracim/tracim/issues/3916#issuecomment-749017122

I have a preference to use the (future) public profile endpoint for that though. The follower/following count looks too specific to me

**Comment by gbonaspetti** [comment]
> > Am I correct?
> 
> I would keep GET /users/<user_id>/following only accessible to the logged user and administrators

The description is the opposite. Followers for all and following for administrators. But I don't see much why not do the same level of security for both.

> 
> > Which endpoint are you talking about ?
> 
> /users/<user_id>/following/summary I think

Me too, but in the description it seems `/users/<user_id>/followers/summary`, so I'm not sure... @grignards?

**Comment by raphj** [comment]
Actually, they are both in the description :-)

**Comment by buxx** [comment]
After read the issue source:

>  Only accessible by when the logged user is <user_id> or is an administrator

is the rule for `/users/<user_id>/following` .

Ok, as I understand, the rules are:

* Know the number of followers: all connected users
* Know the number of following: all connected users
* Know list of user are followers: admins or followed user
* Know list of user are followed: admin of follower user

With that, we have a problem to permit #3909 : If can't know list of following user of an user, impossible to know if this user is following us. Two solutions:

* Permit seeing followed user of a user
* Add a endpoint `/users/<user_id>/is_following_me` which return yes/no

**Comment by raphj** [comment]
yes we can, because this user is in our "followers" list returned by the /users/<user_id>/followers endpoints :-)

**Comment by buxx** [comment]
Good point ! No modification needs. I will begin the dev :)

**Comment by buxx** [comment]
devs done and pull request opened

**Comment by PhilippeAccorsi** [comment]
Done.
