### ISSUE TITLE
Feat: Add a translation api encapsulation

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4054]
## Feature description and goals

Having an automated content translation feature in Tracim can be useful to some use-cases, e.g. international teams.
Several online translation services exist and Tracim should remain as independent as possible from a specific external service so we'll need an encapsulation of those services to use in Tracim.

This encapsulation should be loosely linked to Tracim in order to be easy to split later on (in a separate package/service/…).

It should provide:

- [x] per-"translation service" configuration (API endpoint/API key/…) (see also https://github.com/tracim/tracim/issues/4093)
- [x] document translation (especially HTML): those documents will come from the depot storage in Tracim but the API should avoid to directly use depot, instead an appropriate `io.xxx` class should be used as the document input.
- [x] choice of output language in form of an [ISO-639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
- [x] choice of input language in form of an ISO-639-1 code + a special value indicating "auto-detection of source language"
- [x] ~~possibly a dictionary of translation service specific options that will be given as is to the translation request.~~ Partially implemented. dictionary as valid parameter for translationService. Not given as is to request for now. Need clarification later about how we deal with it.
- ~~possibly a simple text translation (with a string input)~~ Not needed now.

The translation services generally provide two APIs:
- one synchronous APIs for simple text translation (ofter with limitations on the text's length)
- one asynchronous API for longer text translation/document translation

This duality is due to the time taken by the translation of a big document/chunk of text: if only a synchronous API was provided it could lead to request timeouts before the translation is done. It also has the weakness of blocking the caller a possibly long time.

In this first version we will only provide a synchronous python API: if asynchronous requests must be made this will be hidden in the implementation.
The error handling will be done through specific exceptions (do not mix them with Tracim exceptions). The exceptions shall allow to distinguish easily an API usage error (wrong parameters/…) and an API processing error (translation service unavailable/…) .

The initial supported translation service shall be [Systran API](https://translate.systran.net/) (**TODO** add the link to their API documentation).

## Todo for release

- [x] see https://github.com/tracim/tracim/issues/4093 for config changes

## References

- [DeepL Translation API](https://www.deepl.com/docs-api/)
- [Google Translate API](https://cloud.google.com/translate/docs/reference/rest/)
- [Amazon Translate](https://docs.aws.amazon.com/translate/latest/dg/API_Reference.html)

## Time estimation
https://github.com/tracim/tracim/issues/4054#issuecomment-767441815

## Implemented solution
- add TranslationService Abstract class to explain api for such service
- add SystranTranslationService that permit to translate file through systran and get mimetypes/lang supported.
- add somes tests

**Comment by raphj** [comment]
Any idea on automatic tests that can be written for this? Should we write a dummy translation service?

**Comment by grignards** [comment]
> Any idea on automatic tests that can be written for this? Should we write a dummy translation service?

Yes, probably. As much as possible this dummy should entirely be defined in a test fixture.

**Comment by raphj** [comment]
I think we estimated this work to 7 person . days

 - 3 days for the component speaking with the external service (including figuring out how to speak with the service)
 - 2 days for the involved database migrations to add a field giving the state of the translation (none, pending or ready) + the code handling this state
 - 2 days for the Tracim endpoints (#4057)

We went for a version without caching the translation for now right?

**Comment by inkhey** [comment]
> I think we estimated this work to 7 person.day
> 
>     * 3 days for the component speaking with the external service (including figuring out how to speak with the service)
> 
>     * 2 days for the involved database migrations to add a field giving the state of the translation (none, pending or ready) + the code handling this state
> 
>     * 2 days for the Tracim endpoints (#4057)
> 
> 
> I'd add 1 person.day for #4093 to this 7 person.day figure.
> 
> We went for a version without caching the translation for now right?

If we just went for the version without caching we may not need no to handle database. this mean only 6 person.day including endpoints and config parameters.

**Comment by lebouquetin** [comment]
> If we just went for the version without caching we may not need no to handle database. this mean only 6 person.day including endpoints and config parameters.

Hm ... caching should not be related to database

**Comment by inkhey** [comment]
Just begin to try a simple api for translation, it's just a POC, some separation are probably uneeded yet (separation between TranslateService and Translator for exemple, as we can accept a systran only api for now and split later the code).
I have some technical question about this:
- How to define input_lang/output_lang object properly ? I go for object but this is far from nice, enum don't seems usable there, i will say in this specific case tupe may be a solution. (namedtuple maybe ?)
- Do we expect to anticipate sync/async call now and so on add "sync_translate" method ?
- How to we expect file to be given, i was thinking of a filestream but should it always been binary to handle all case so we do need to reconvert binary to text here in some specific case ? How we expect to say we do support this or this kind of file ? i do suggest mimetype.
- probably some others things...
```
import io
from abc import ABC
from abc import abstractmethod
from typing import IO
from typing import List
from typing import Optional


class FileNotTranslatable(Exception):
    pass


class TranslationNode:
    def __init__(self, input_lang: str, output_lang: Optional[str]):
        self.input_lang = input_lang
        self.output_lang = output_lang

    def __eq__(self, other):
        if isinstance(other, TranslationNode):
            return (
                self.input_lang == other.input_lang and
                self.output_lang == other.output_lang
            )
        return False


class TranslateService(ABC):

    @abstractmethod
    def translate(
        self,
        translate_node,
        file_buffer,
    ):
        pass

    @property
    @abstractmethod
    def name(self):
        pass

    @property
    @abstractmethod
    def supported_nodes(self):
        pass


class UpperCaseTranslateService(TranslateService):

    @property
    def name(self):
        return 'uppercase'

    def translate(
        self,
        translate_node,
        file_buffer: IO,
    ):
        return str(file_buffer.read()).upper()

    @property
    def supported_nodes(self):
        return [
            TranslationNode('fr', 'en'),
            TranslationNode('en', 'fr'),
        ]

class Translator:

    def __init__(self, translate_services: List[TranslateService]):
        self.translate_services = translate_services

    def translate(
        self,
        input_lang: str,
        output_lang: str,
        file_buffer,
    ):
        current_node = TranslationNode(input_lang, output_lang)
        for backend in self.translate_services:
            for backend_node in backend.supported_nodes:
                if current_node == backend_node:
                    return self._translate(current_node, backend, file_buffer)
        raise FileNotTranslatable()

    def _translate(
        self,
        translation_node: TranslationNode,
        backend: TranslateService,
        file_buffer,
    ):
        return backend.translate(translation_node, file_buffer)


if __name__ == "__main__":
    my_string = io.StringIO('Super journée !!!')
    translator = Translator([UpperCaseTranslateService()])
    result = translator.translate(
        'fr',
        'en',
        my_string
    )
    print(result)
    translator.translate(
        'fr', 'de', my_string
    )

```

**Comment by raphj** [comment]
TranslationNode → TranslationLanguagePair?
