### ISSUE TITLE
Feat: Add configuration parameters for the translation service

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4093]
## Feature description and goals

Tracim will provide a content translation feature (for now limited to notes and comments) using a third-party translation service.
The translation service interaction will be abstracted away in #4054 and the needed endpoints added in #4057.
For #4057 we need configuration parameters in order to configure #4054.

- [x] `translation_service.enabled`: boolean returned in `system/config` so that the frontend can know when to display the translation interface elements
- [x] `translation_service.provider`: string that configures the translation service provider (for now we'll only support `systran` here)
- [x] `translation_service.systran.api_url`: configures the systran API base URL
- [x] `translation_service.systran.api_key`: configures the systran API key

## Todo for release

- [ ] document about the new parameter/feature in changelog

## Prerequisites

- #4054

## Implemented solution
- add 4 configurations parameters to tracim with documentation about translation service feature using systran

**Comment by raphj** [comment]
I suggest `translation_service.provider` instead of `translation_service.type`, what do you think?

**Comment by raphj** [comment]
1 man.day?

**Comment by grignards** [comment]
> I suggest `translation_service.provider` instead of `translation_service.type`, what do you think?

Why not, I put `type` since it was used in similar cases, but here `provider` would be a better fit.

**Comment by raphj** [comment]
Indeed. Both suit me. @PhilippeAccorsi any preference?

**Comment by inkhey** [comment]
> 1 man.day?

I was thinking of 1/2 man.day as i far in understood, it's just config parameter +(system/config endpoint) updating and all the complexity is in translation api (we just give parameter to translation api).

**Comment by PhilippeAccorsi** [comment]
> Indeed. Both suit me. @PhilippeAccorsi any preference?

Translation service can be running localy ? If yes, can we have this kind of  `translation_service.provider = local` configuration in the futur ?

If we use `translation_service.type` for me value is `local` or `external` and not the name of service (I not know if the name of service is important here).

**Comment by grignards** [comment]
> > Indeed. Both suit me. @PhilippeAccorsi any preference?
> 
> Translation service can be running localy ? If yes, can we have this kind of `translation_service.provider = local` configuration in the futur ?

Currently not, we could imagine it in a (far?) future.

> If we use `translation_service.type` for me value is `local` or `external` and not the name of service (I not know if the name of service is important here).

OK, then let's go for `provider`.

**Comment by PhilippeAccorsi** [comment]
Done.
