### ISSUE TITLE
Feat: Add faceted search for contents (improvement of existing search content endpoint)

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4094]
## Feature description and goals

The search functionality in Tracim is simple but misses several filter possibilities. The elasticsearch search backend allows use to easily return [facets](https://en.wikipedia.org/wiki/Faceted_search) so that users can refine their search criteria.

- [x] add the `search_engine` parameter in `/api/system/config`. The value of this parameter comes from `SEARCH__ENGINE`. [note: this as been merged as commit 2f82cc5f2f2cf139ac3e85a21512465268db05b7 in develop]
- [x] keep the current simple search api/ and controller under `/api/search/content`. It can always be active.
- [x] when enabled the elasticsearch api should be available under `/api/advanced_search/content`
- [x] return simple facets with the search results in a `facets` list. All facets are returned. Simple facets are:
  - [x] `workspace_names`
  - [x] `statuses`
  - [x] `content_types` (file/html-document/...)
  - [x] `file_extensions` (.jpg/…): take care to lowercase the search here.
  - [x] `author__public_names` (of the first revision)
  - [X] `last_modifier__public_names` (of the current revision)
Simple facets should be returned as a list of `{value, count}` objects:
```json
{
  "file_extensions": [
    { "value": ".pdf", "count": 42 },
    { "value": ".json", "count": 23 },
  ]
```
- [X] return modified and created date ranges with the search results:
    ```
    "modified_range": {
        "from": "2020/12/01T22:23:24", "to": "2020/12/01T22:23:24"
    }

    "created_range": {
      "from": "2020/12/01T22:23:24", "to": "2020/12/01T22:23:24"
    }
    ```
- [x] add a `search_fields` query parameter. Its value is a comma (`,`) separated list of keywords. The possible keywords will be `raw_content`, `comments`, `description` and `label`. The default value will be the complete list. This list shall be used to restrict the search to the given content's fields.
- [x] return the used searched fields as a list:
```json
"search_fields": [
    "label",
    "raw_content",
    "comments",
    "description"
  ],
```
- [x] add query parameters for all simple facets. Each parameter is a comma separated list (`,`) of values. :warning: commas in values shall be escaped:
  - [x] `content_types`
  - [x] `workspace_names`
  - [x] … see simple facet list
 - [x] add query parameters created and modified ranges:
   - [x] `created_from` and `created_to`
   - [x] `modified_from` and `modified_to`
- [x] apply the pending fix about lang based indexing: https://github.com/tracim/tracim/issues/2659 ? ( this commit in particular: https://github.com/tracim/tracim/commit/f15ea6c7f4a0d54a967a87e2465479f9bd380858)

see also:
https://github.com/tracim/tracim/issues/4085

## The content's path

The content path will be returned by the search endpoint in the same key as the current search endpoint and in the same form of the specific endpoint for path.

The only change for the frontend is the removal of the key `parent_id` which isn't used by the frontend.

As seen in https://github.com/tracim/tracim/issues/4146, the elastic search indexes will be updated for every move and rename of content so that the content path will always stay up to date.

## Todo for release

- [ ]  This fix required to reindex the data to have a working search

## Example

```
GET /api/search/content?
page_nb=1&
search_string=toto&
search_fields=label,content,comments&
content_types=file,folder&
file_extensions=.jpg,.pdf&
created_from=2021-01-26T08:49:03.018Z&
created_to=2021-01-26T08:49:03.018Z&
updated_from=2021-01-26T08:49:03.018Z&
updated_to=2021-01-26T08:49:03.018Z&
show_archived=0&
show_deleted=0&
size=10
```
```json
{
  "contents": [
    {
      "author": {
        "has_avatar": true,
        "has_cover": true,
        "public_name": "John Doe",
        "user_id": 3,
        "username": "My-Power_User99"
      },
      "content_id": 6,
      "content_namespace": "content",
      "content_type": "html-document",
      "created": "2021-01-26T08:49:03.018Z",
      "current_revision_id": 12,
      "current_revision_type": "creation",
      "file_extension": ".txt",
      "filename": "nameofthefile.txt",
      "is_active": true,
      "is_archived": false,
      "is_deleted": false,
      "is_editable": true,
      "label": "Intervention Report 12",
      "last_modifier": {
        "has_avatar": true,
        "has_cover": true,
        "public_name": "John Doe",
        "user_id": 3,
        "username": "My-Power_User99"
      },
      "modified": "2021-01-26T08:49:03.018Z",
      "score": 0,
      "show_in_ui": true,
      "slug": "intervention-report-12",
      "status": "closed-deprecated",
      "sub_content_types": [
        "html-content"
      ],
      "workspace": {
        "label": "Intranet",
        "slug": "intranet",
        "workspace_id": 19
      },
      "workspace_id": 19
    }
  ],
  "facets": {
    "content_types": [
        {"value": "file", "count": 2},
        {"value": "folder", "count":  1}
     ],
    "file_extensions": [
      {"value": ".pdf", "count": 1},
      {"value": ".odt", "count": 1}
    ]
  },
  "created_range":
  {
    "from": "2021-01-26T08:49:03.018Z",
    "to": "2021-01-26T08:49:03.018Z",
  },
  "modified_range":
  {
    "from": "2021-01-26T08:49:03.018Z",
    "to": "2021-01-26T08:49:03.018Z",
  },
  "search_fields": [
    "filename",
    "raw_content",
    "comments"
  ],
  "is_total_hits_accurate": true,
  "total_hits": 0
}
```

## Prerequisites
- #4146

**Comment by inkhey** [comment]
current elasticsearch model (indexed): https://github.com/tracim/tracim/blob/develop/backend/tracim_backend/lib/search/elasticsearch_search/es_models.py

**Comment by inkhey** [comment]
### These current Elasticsearch field data could be deprecated due to fact they are related to other data:
- `parent/parents` to get the breadcrumb : Deprecated if you move files in same workspace/ move 
- `archived_through_parent_id/deleted_through_parent_id` : Needed to avoid inaccessible field in result. may be solved by a better refactor/clarification of the deleted/archived behavior with children.
-  `last_modifier` : name/etc..
-  `author` : name/etc..
-  `workspace` : name/etc..
### Theses fields are related to others data, but should probably not being deprecated:
- `workspace_id` should always being good has moving a directory to another workspace cause creating new event for all content (unlike deletion/archive).
- `workspace`: the other data related to workspace may be deprecated : name, etc... if workspace update.
- `comments` : at each update of comments, comment do update their parents, comments are not stored in search index by themself.
### Other points to notice:
- `modified` : this field do NOT take into account comments and sub content. (note: we do index only the parent, when there is modification on a comment).
-  `last_modifier` : same as modified, don't take comments into account
-  `is_active, is_archived, is_deleted` : content specific, do NOT take into account parent (a content where parent is deleted may be currently not deleted but should probably not being visible). see also `archived_through_parent_id/deleted_through_parent_id`.
- `show_in_ui`: this field is not used at all for now.
- `is_editable` and `is_active` are data inferred from other field (editable => open status, active = > not archived, not deleted.

**Comment by inkhey** [comment]
Somes ideas to solve issues related to slated data:
- refactor properly the deletions/archive feature, to have a clear logic: This one is really tricky !
- refactor the move feature in same workspace: any good reason to not update sub-content here ?
- accept deprecated data: may be acceptable for some, less for other: see deleted files ...
- partial update of subcontent by index, when updating the parent
- regular update of all/part of the index.

**Comment by inkhey** [comment]
>  keep the current simple search api/ and controller under /api/search/content. It can always be active(?)

if we do use 2 different endpoint:
- /api/search/content
- /api/advanced_search/content
i don't see much reasons to not let it active, unless this mean a bit more work.

>  its comments (! recursively?)

No need to be recursive now, comments of comments are not supported in ui now.

>  (with .html for notes?)
note and thread as already specific extensions in `.something.html`, but i'm not sure we should store them in search.

**Comment by Skylsmoi** [comment]
About the file path, the basic search already displays the list of parents.

It is updated properly when moving or renaming the content and update each parts of the path (not just the direct parent).

So I would assume it's possible for the endpoint to returns the same information for the advanced search.

@grignards @inkhey can you confirm it's not an issue ? 
Also confirm that the current implementation for the basic search won't create some performance issues please

**Comment by inkhey** [comment]
> About the file path, the basic search already displays the list of parents.
> 
> It is updated properly when moving or renaming the content and update each parts of the path (not just the direct parent).
> 
> So I would assume it's possible for the endpoint to returns the same information for the advanced search.
> 
> @grignards @inkhey can you confirm it's not an issue ?
> Also confirm that the current implementation for the basic search won't create some performance issues please
> 
> Update the issue (part The content's path) with the information

We should index them, see https://github.com/tracim/tracim/issues/4146. Not problem to index them.

**Comment by gbonaspetti** [comment]
what are the possible values of `search_engine`?

**Comment by inkhey** [comment]
> what are the possible values of `search_engine`?

`simple` and `elasticsearch`, like `search.engine` config param values

**Comment by inkhey** [comment]
Question about naming, why  `workspace_names` and `author__public_names` ?
The naming of both theses fields doesn't follow the same rules.

**Comment by raphj** [comment]
@inkhey please suggest names :-)

I was not involved in picking these names, the double underscores sure feel a bit weird.

**Comment by lebouquetin** [comment]
Double underscores allow to add semantic when you have naming with several parts.

**Comment by lebouquetin** [comment]
@raphj look at the coding rules: https://algoo.tracim.fr/ui/workspaces/11/contents/html-document/16720

**Comment by inkhey** [comment]
> @inkhey please suggest names :-)
> 
> I was not involved in picking these names, the double underscores sure feel a bit weird.

If we do want have same rules, we should probably use `workspace__labels` instead of ` workspace_names`. No need to change the others fields.

**Comment by raphj** [comment]
@lebouquetin I've seen this in the test methods but not in the objects returned by the API

**Comment by grignards** [comment]
> > @inkhey please suggest names :-)
> > I was not involved in picking these names, the double underscores sure feel a bit weird.
> 
> If we do want have same rules, we should probably use `workspace__labels` instead of ` workspace_names`. No need to change the others fields.

In general I use the `__` to make clear which words are groupe *if there are more than 2* in the name (if there are only two, I keep only one `_` as the relation between the two words is intuitive).

**Comment by raphj** [comment]
let's settle on this then.

**Comment by inkhey** [comment]
tested, work as expected.

**Comment by PhilippeAccorsi** [comment]
Done.
