### ISSUE TITLE
Feat: Add faceted search for spaces

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4134]
## Feature description and goals

Add support for search on workspace with elasticsearch search
- [x] Add endpoint `GET /api/advanced_search/workspace` ~~or `GET /api/search/spaces`~~ for elasticsearch search only
- [x] Add workspace index for elasticsearch search that can be created and indexed using tracimcli command, at the same time of other index.These fields should be indexed: 
  - label
  - description
  - workspace id
  - is_deleted (probably, depending how we deal with deleted workspace
  - owner (containing user id and public_name, username too ?)
  - members (containing user id and public_name, username too ?)
- [x] Add search on workspace using elasticsearch with the required facets (see https://github.com/tracim/tracim/issues/4097)
- [x] Add indexation of workspace:
  - on workspace creation/update/deletion
  - on workspace members add/remove (on role changing too ?)
  - on user update : update of author name
  - …?
- [x] Filter so that: 
  - search does not return workspaces which are not visible for the current user
  - search does not return users in open/on_request space (from facets).

## Todo for release

- [ ]  This fix required to reindex the data to have a working search

## Prerequisites

- #4094
- #4147
- #4149

## Extra information
similar issue for users: https://github.com/tracim/tracim/issues/4095

**Comment by inkhey** [comment]
according to current https://github.com/tracim/tracim/issues/4094 spec, the logical endpoint naming should be:
`GET /api/advanced_search/workspaces`

**Comment by inkhey** [comment]
Tested, work as expected.

**Comment by PhilippeAccorsi** [comment]
Done.
