### ISSUE TITLE
Misc: add multi-index capability to ESSearchApi

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4147]
## Feature description and goals

The elastic search will be improved to add users and spaces. Those need separate indexes.
The `tracimcli` command should work on multiples indexes at the same time instead of one index only:

- [x] the following command should create all needed indexes for tracim search with elasticsearch
```shell
  search index-create  create index of search engine
```

- [x] the following command should delete all indices.
```shell
  search search index-drop  Delete all index, alias and template of tracim document
```

- [x] the following command should populate all indices.
```shell
  search index-populate  index content(s) into search engine
```

- [x] the following command should upgrade all indices the same way the current behavior work (goal is allowing "hot migration"), if this is too difficult, we may decide to simply drop it for now.
```shell
  search index-upgrade-experimental  upgrade index: create a copy of current index with updated in
```

- [x] to ensure proper functionality developed in this issue, the `users` and `workspaces` indices should be created (even if empty).

- [x] Rename the `search.elasticsearch.index_alias` configuration parameter to `search.elasticsearch.index_alias__prefix` and use it as a prefix when creating indices (for example `tracim` here  and default template will create `tracim-users-{date}`, `tracim-contents-{date}`, `tracim-workspaces-{date}`.

## Example configuration parameters

```ini
# main index alias use to search/index content in elasticsearch
search.elasticsearch.index_alias_prefix = tracim
# template_name for all index created currently only {index_alias} and {date} variable are usable.
# be careful this template is used to find all index to delete with tracimcli search delete command
# default value is "{index_alias}-{date}"
search.elasticsearch.index_pattern_template = {index_alias}-{date}
```

About the code organization, there are no strict requirements, `ESSearchApi` may be directly modify to handle all index, but it seems probably simpler to split the "one index logic" in a separate object.

## Todo for release

- [ ] change of naming in the configuration: `search.elasticsearch.index_alias` -> `search.elasticsearch.index_alias_prefix` as there will be multiple ES indices from now.
- [ ] update of the ES indices will be needed with `tracimcli`

**Comment by Skylsmoi** [comment]
test result:
- without the parameter `search.elasticsearch.index_alias_prefix = tracim`, the tracimcli commands seemed to fail silently
- `tracimcli search index-upgrade-experimental` returned `Something goes wrong during command: 'ESSearchApi' object has no attribute 'migrate_index'`
- `tracimcli search index-drop` returned:
```
delete index
Something goes wrong during command: 'ESSearchApi' object has no attribute 'delete_index'
```

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
@grignards Missing check in `Todo for release`
This issue is it related to new feature or not ? Is it necessary to add issue number in changelog or its just necessary to add information about breaking change.

**Comment by grignards** [comment]
> @grignards Missing check in `Todo for release`
> This issue is it related to new feature or not ? Is it necessary to add issue number in changelog or its just necessary to add information about breaking change.

Just the information about the breaking change I thought the "add to changelog" label was also used to flag issues related to breaking changes.

**Comment by grignards** [comment]
> @grignards Missing check in `Todo for release`
> This issue is it related to new feature or not ? Is it necessary to add issue number in changelog or its just necessary to add information about breaking change.

I'm unclear about this: what is the aim of these checks?

**Comment by PhilippeAccorsi** [comment]
> > @grignards Missing check in `Todo for release`
> > This issue is it related to new feature or not ? Is it necessary to add issue number in changelog or its just necessary to add information about breaking change.
> 
> Just the information about the breaking change I thought the "add to changelog" label was also used to flag issues related to breaking changes.

Its true. It's my mistake about label :)
Good label here.

**Comment by PhilippeAccorsi** [comment]
> > @grignards Missing check in `Todo for release`
> > This issue is it related to new feature or not ? Is it necessary to add issue number in changelog or its just necessary to add information about breaking change.
> 
> I'm unclear about this: what is the aim of these checks?

To close issue, i review issue to make sure all its done. I just need to be sure all its done so maybe check is not necessary here.

**Comment by PhilippeAccorsi** [comment]
Done.
