### ISSUE TITLE
[META] Feat: Add tag to contents

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4681]
## Feature description and goals

Tags are meant to characterize content. It should be possible to create tags per space and link those tags to any content in that space. One tag can be linked to several contents, one content can have several tags.

To do:
- [ ] Create tag contents (at space settings? new page?)
- [ ] Modify a tag
- [ ] Delete a tag
- [ ] List tags
- [ ] Link a tag to a content
- [ ] Delete a content tag
- [ ] List tags from a content

## Prerequisites

None

## To be discussed before development

This issue can/should be split into smaller issues. The interface should be discussed.
