### ISSUE TITLE
[META] Request to call someone

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4855]
#4843 
## Feature description and goals

- [ ] feat : have flash messages on all tabs
- [ ] feat : have the ability to write a message to someone when called (the called person will then be able to read this message on the pop-up). 
- [ ] feat : have a notification on the wall that someone has called
- [ ] bug : incoherence between call time and flash message reception time
- [ ] bug : information lost if you close the flash message (link)

## Translations

|English|French|Portuguese|German|
|-|-|-|-|
|{{author}} tried to call you |{{author}} a essayé de vous appeler|{{author}} tentou telefonar-lhe|{{author}} hat versucht, dich anzurufen|

_The translation can be rediscussed_

## Prerequisites

None

**Comment by charline-rageade** [comment]
@MariePrandstetter i've edit ticket with a new feature
