### ISSUE TITLE
Meta: Improvements to concourse CI

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4886]
## Feature description and goals

Tracim started using a custom concourse CI with this issue : #4828.
This first version has several shortcomings that could be addressed:

- [ ] the docker instance started for backend tests needs cgroup v1 (due to the startup script), a v2-compatible version could be useful to avoid the future deprecated status of v1.
- [ ] currently the pipeline only tests pull-requests, not other branches (`develop`, `master`…) on a regular basis
- [ ] as there are no `develop` build, the project's badge is not updated. This is do-able with concourse: https://concourse-ci.org/observation.html
- [ ] the docker image `algooci/tracim` used for all tests is not generated automatically. It could be generated whenever a change on the backend/frontend dependencies is introduced.
- [ ] the frontend build does not directly uses the modules installed in the docker image (but skips the download as they are present). Finding a way to use them would gain some minutes (around 3).
- [ ] pending pull-requests builds aren't aborted if a new commit is added to the PR. This could be done either by using the `fly` command directly or with [this resource](https://github.com/troykinsella/concourse-fly-resource)
- [ ] two custom docker images (elasticsearch-ingest and pushpin) are built during backend tests, building them beforehand and uploading them to algooci/... would gain some time (probably around 5 minutes).
- [ ] the pull-requests are monitored every 30 seconds which becomes a minimum delay between a push and a build. This could be improved by using a github webhook. This has not been done because this would require one hook per pull-request (as the hook callback in concourse is specific to each pipeline). [This project](https://github.com/schmurfy/webhook-broadcaster) could be used to mitigate this difficulty.

## Prerequisites

Discuss which tasks are to be done (and their order).

**Comment by PhilippeAccorsi** [comment]
- Concourse not use docker mirror correctly (missing configuration in pipeline ?)
- it is not possible to stop/start db test individually
- PR merged or canceled are not removed in concourse

**Comment by PhilippeAccorsi** [comment]
@Millefeuille42 @Skylsmoi @floreal15 @lebouquetin FYI :)
