### ISSUE TITLE
Bug: Failing tests on develop and technical debt on grouped notifications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4895]
## Description and expectations

To do:
- [x] Fix failing tests on develop (p0)
- [x] Fix technical debt on translation files https://github.com/tracim/tracim/pull/4892#discussion_r700199451 (p0)
- [x] Fix technical debt on group notification types https://github.com/tracim/tracim/pull/4892#discussion_r700228425 (p0)
- [x] Fix disabled tests at frontend/test/src/component/OpenContentApp.spec.js (p0)
- [x] Add tests for #3797  (p0)

### Version information

- Tracim version: v3.10

________________________________________________

## Prerequisites

PR: #5061

**Comment by lebouquetin** [comment]
My feeling is this is not *p0* (as it may be fixed with a future maintainance release like 3.10.2 for example)

**Comment by raphj** [comment]
By the way if failing tests are unit tests, I fixed them yesterday (it was quick to do). I agree that it can wait a bit.

**Comment by MariePrandstetter** [comment]
link to the closed ticket #4969

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by MariePrandstetter** [comment]
Done.
