### ISSUE TITLE
[META] Feat:  improve the UX of Kanban

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4962]
## Feature description and goals

- [x] possibility to unfold/fold a ticket
  - We will see if this feature is necessary for a next version
- [x] improve the overview of the table
- [x] markdown in ticket

## Prerequisites

N/A

**Comment by charline-rageade** [comment]
> What do you mean?

@raphj To be able to see all the columns more easily. 

> (also, the title of the issue is a bit broad, making it harder to search, I'd suggest separate issues for separate topics).

I'm making a note on my to-do list

**Comment by raphj** [comment]
> To be able to see all the columns more easily

Do you have a precise idea on how to achieve this?

**Comment by charline-rageade** [comment]
>Do you have a precise idea on how to achieve this?

not yet, I need to take some time to reflect on this.

**Comment by raphj** [comment]
Okay, thank you!

**Comment by MariePrandstetter** [comment]
Here are some mockups to start a discussion about how to implement the kanban.

First of all, there are some general topics we will need to discuss :
- Should we keep the term "kanban", or use "board" ? I think it depends on how flexible we want this functionality to be.

This mockup shows how the user will create a new kanban. They click on the button "create a new kanban" at the bottom of the list of create content buttons. I chose an icon that looks like two columns to remind of the kanban. I'm curious if you think this is explicit enought.
![Frame 1](https://user-images.githubusercontent.com/50776142/141434798-88141189-7ee5-4a65-bfde-871a4ec40374.png)

Once the user has clicked on this button, they are redirected to the content list page, with a popup that asks what's the name of the kanban. I was wondering if maybe we could also ask the user for the name of the first column, but there could be cases where a user just wants to create an empty board.
![Frame 8](https://user-images.githubusercontent.com/50776142/141434830-3d8207cb-b898-4eef-b309-26594424efec.png)

This is an empty board. I tried to give as much information as possible for the user to be guided to create columns or "cases" (I'm still unsure about how to call each "task" in the columns, since each ticket/case could mean something else than a task. But this brings us back to the question of how flexible we want to be with this feature). 
![empty kanban](https://user-images.githubusercontent.com/50776142/141434868-8fffa467-6b6a-46d2-bbf3-2b1ded6236b4.png)

When the user clicks on "Créer une case", a popup shows with a list of required information. I think we will need to discuss what information is required here. 
![kanban add caser](https://user-images.githubusercontent.com/50776142/141434888-85115141-8e53-498e-8853-6d1d71dba9e1.png)

When the user clicks on "Créer une colonne", this popup shows. If there are just changing an existing column the title of the popup will be "Modifier une colonne", and if they create one it will be "Créer une colonne"
![kanban add column](https://user-images.githubusercontent.com/50776142/141434915-59f912c9-d394-4fa8-b52a-3268f06d0c5d.png)

If the user tries to leave this page, for example by clicking somewhere else in the page, or by closing the tab, this warning popup will show up.
![kanban warning](https://user-images.githubusercontent.com/50776142/141435036-d35f4bb5-d739-4071-a52c-70d55fe64b80.png)

This is the read mode of the feature. Users that are "reader only" will see this, or any user that wants to see this content in "read only" mode.
![kanban lecteur](https://user-images.githubusercontent.com/50776142/141434994-46fa6a4f-fddf-4c4e-9fb8-f557a9e50a11.png)

This is the full screen version of the kanban. I tried a different styling on the tasks here, with a border around each task instead of a colored title. Let me know what you think about this.
![kanban fullscreen](https://user-images.githubusercontent.com/50776142/141435007-600598cc-b74f-45b8-b54e-629893e782b1.png)

**Comment by charline-rageade** [comment]
@MariePrandstetter on the third picture you talk about "creating a box" (créer une case), I thought I was expecting to create a card (créer une carte).

**Comment by MariePrandstetter** [comment]
> @MariePrandstetter on the third picture you talk about "creating a box" (créer une case), I thought I was expecting to create a card (créer une carte).

Yes, I'm still unsure about how to call that. "Card" seems good. But there seem to be several options : 
- Card
- Box
- Task
- Ticket

**Comment by inkhey** [comment]
Point to consider:
- are we sure we do want kanban to be a file in the standard file hierarchy ?
- section ? To be able to have proper ordering, instead of saving the order of items (which may be tricky depending on the implementation, i do suggest to have some kind of section of card.
- Link a card to a content ? It may be nice to have some kind of connection between card and content. If so, it may be useful to edit/ get access to card from the content.

**Comment by charline-rageade** [comment]
@inkhey @MariePrandstetter 
> Link a card to a content ? It may be nice to have some kind of connection between card and content. If so, it may be useful to edit/ get access to card from the content.

At the OSXP we got feedback that it would be interesting to be able to link a card to content.

**Comment by raphj** [comment]
> > @MariePrandstetter on the third picture you talk about "creating a box" (créer une case), I thought I was expecting to create a card (créer une carte).
> 
> Yes, I'm still unsure about how to call that. "Card" seems good. But there seem to be several options :
> 
>     * Card
> 
>     * Box
> 
>     * Task
> 
>     * Ticket

Card sounds standard. Box, less. Task and ticket seem more (too) specific

**Comment by gbonaspetti** [comment]
> > @MariePrandstetter on the third picture you talk about "creating a box" (créer une case), I thought I was expecting to create a card (créer une carte).
> 
> Yes, I'm still unsure about how to call that. "Card" seems good. But there seem to be several options :
> 
> * Card
> * Box
> * Task
> * Ticket

I like Card, Task remind me the ToDo feature #2841 .

About the rest:

-  I love the color integrate to the border.
- I ask myself if the popups shouldn't be in the app color.
- Should we stay with the same color that app file or have a kanban color (like news)?
- Should the "quit fullscreen" button appears only on hover? Like that we do not hide a column if we have multiples.
- Idea for the ... menu on each card: https://github.com/tracim/tracim/issues/4193 
- Some other ideas: have an number id for card (easy to identify on comments), https://github.com/tracim/tracim/issues/4961, https://github.com/tracim/tracim/issues/4222, https://github.com/tracim/tracim/issues/4189

**Comment by raphj** [comment]
I also like the look of these mockups, well done!

**Comment by MariePrandstetter** [comment]
I've gathered some additional feedback based on these mockups: 
- We should think about the wording of "members", and "deadline" (date limite) in the card popup, it is not explicit enough 
- Should this popup be yellow like the color app?
- Remember to add the kanban logo, or warning logo in the warning popup
- Show a mockup where the user doesn't choose any color, in order to show the default colors
- Add more border radius on the cards

For the saving of the kanban (one of the main issues for this feature): 
- We could save each time a card or column popup is validated
- When the user moves cards around, the button "validate" shows up at the bottom of the app (like it is designed in the mockups)

Feature ideas: 
- Enable the storing of cards that are marked as "done"
- Have a "WIP" column that has a limited number of cards (ex: maximum 5 cards in the column "WIP")

**Comment by MariePrandstetter** [comment]
Here are some additional mockups with an alternative design for the columns. The grey version is when the user chooses to not customize any column and to keep the default color.

![kanban fullscreen colored columns](https://user-images.githubusercontent.com/50776142/142212038-e92d834d-2bc8-4317-8f8d-c36676f2030a.png)
![kanban fullscreen grey columns](https://user-images.githubusercontent.com/50776142/142212040-27ce42c9-25df-4a82-b002-6d16ecb3994e.png)

**Comment by PhilippeAccorsi** [comment]
- L'espace blanc au dessus des card c'est pour les bouton quand on est en édition ? (un petit screen permettrait de mieux se rendre compte si c'est le cas).
- Ne pourrait-on pas plutôt avoir la durée et la date sur la même ligne ?
  - et la date en rouge si on a dépassé plutôt que du texte ? (cela ferait moins d'élément où gérer la traduction)
- j'aime bien le rendu, et c'est bien parlant aussi quand il y a de la couleur
- ne peut-on pas avoir de la couleur aussi par card ? (genre la vue en gris mais certaine card en couleur)
- le bouton de réduction du plein écran me pose question
  - comment sera géré le scroll horizontal (et comment sera-t-il positionné par rapport au bouton du plein écran)

**Comment by knodelle** [comment]
I got the following feedbacks for the different mockups : 

For the V1 : 
-  @raphj has a preference for this one
  - it gives the most freedom for the colors, without being overwhelming

For the V2 : 
- @gbonaspetti has a preference for this one
  - gives freedom for color usage, and solves the problem of having a colored background on a text

For the V3 : 
- For now, it is the least favorite 
- Feedback that the colors could be too flashy
- No possibility of having color in the cards

**Comment by inkhey** [comment]
@knodelle I like the last one, maybe try different background for it (light grey/blue/green but also image) ?

**Comment by knodelle** [comment]
> @knodelle I like the last one, maybe try different background for it (light grey/blue/green but also image) ?

Thanks @inkhey :) You mean a general background for the whole kanban app or for each column ?

I see most of you in the team like the last mockup the most :D

**Comment by inkhey** [comment]
I'm thinking about the whole kanban app. Another alternative to image to make a background a bit less boring may be a small gradiant (from up to bottom ?)

**Comment by knodelle** [comment]
Ok I'll try one version with a colored background (probably the kanban logo color)

**Comment by knodelle** [comment]
done
