### ISSUE TITLE
[META] Bug: fix some interface details issues 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5052]
## Description and expectations

- [ ] Missing the right margin of the file preview: the '5 de 5' is too close to the right bar compared to the other elements of a file.
![ELEKeAe](https://user-images.githubusercontent.com/35422692/139832652-112ecec4-8e9d-49e0-b2b2-91a681676ed4.png)
- [ ] Emojis go beyond the header on a small screen.
![VKuBpRi](https://user-images.githubusercontent.com/35422692/139832583-71eeb7e3-a842-4c4d-9af1-95f2b6a16bc5.png)
- [ ] There is no border when there is only one result in the search or favorites.
![BW3iKKS](https://user-images.githubusercontent.com/35422692/139832528-1ffb3509-8abf-443a-bf69-47d379cb472c.png)
- [ ] The reactions are not aligned with the reaction button in recent activities and file type publications, also the button is too far to the right.
![UDqf7cf](https://user-images.githubusercontent.com/35422692/139832422-7d4c3e95-4c19-4674-8dc5-aa693ab98eaa.png)

### Version information

- Tracim version: v4.0
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

**Comment by inkhey** [comment]
Another issue with many reaction on desktop computer: ![Capture du 2022-05-25 10-24-07](https://user-images.githubusercontent.com/7851652/170217037-f437e622-38e2-43a8-95f0-ef68b7e6c8be.png)
