### ISSUE TITLE
[META] Feat: Kanban improvements and bug fix 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5129]
## Feature description and goals

Linked PR : #5150 

P0
- [x] backend error `join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`
  - reproducible by creating a kanban (so only 1 revision) and then creating a second revision that does not save a new version of the file:
    - status change
    - deletion
    - renaming ? (broken because of another problem)
  - explanation: Contrary to the file, we do not create a second revision with content, this case is neither managed by the frontend (by detecting the "empty" case for another revision than the 1st one) nor managed by the backend (by automatically creating an "empty" kanban content). A simple solution could be that the kanban creation is done from a pre-existing template. NOTE: This must be fixed by settign an empty file at file content creation time (which will fix also other side effects like 400 or 500 on preview when a content is not yet filled)
- [x] impossible to scroll horizontally
- [x] fix comments from review #5119 
- [x] js crash `Uncaught TypeError: e is undefined` when a kanban column is moved
- [x] app refresh problem. wrong url called, so backend refuses: `{"message": "revision 59574 is not a revision of content 19726", "details": {"error_detail": {}}, "code": null}`. Obtainable by switching between 2 kanbans.
- [x] the color of a column is automatically saved and creates many revisions
- [x] impossible to change the title of a kanban board
- [x] if a kanban is deleted, it cannot be restored
- [x] impossible to scroll vertically to the end of the kanban (multiple cards in the same column)
- [x] add tinymce instead of "Enable HTML" in creation popup 
- [x] update popup design to be minimally usable

P1
- [x] change "duration" wording to "value" (which allow to use as a duration, or as an amount of points, or as a value in euros, etc)
- [x] missing translations for Kanban
- [x] there are different ways to add a column depending on my rights (contributor: square with +, space manager: + column in the header)
- [x] we have the button to add a column when the content is not open (status)
- [x] there is no maximum width for a column, it adapts to the length of the title
- [x] kanban notifications do not redirect to the right content [backend]

**Comment by lebouquetin** [comment]
@gbonaspetti I reordered the priorities. I'd like to have a talk when P0 and P1 are fixed in order to re-order remaining stuff

Note: I added P3 (which is low priority) and backlog (which means "no priority")

**Comment by gbonaspetti** [comment]
> @gbonaspetti I reordered the priorities. I'd like to have a talk when P0 and P1 are fixed in order to re-order remaining stuff
> 
> Note: I added P3 (which is low priority) and backlog (which means "no priority")

ok, perfect, thx

**Comment by charline-rageade** [comment]
background tests, P2 and more are in #5153 !

**Comment by gbonaspetti** [comment]
thx. tested on branch.

**Comment by knodelle** [comment]
done
