### ISSUE TITLE
[META] Feat: Add responsiveness to Tracim (mobile)

### ISSUE THREAD

**Issue by MariePrandstetter** [tracim/tracim#5134]
## Feature description and goals

p0:
- [ ] Some of the popups are not closeable which is a problem since I have to wait/make the popup disappear to keep using the application.
- [ ] Missing text in several menu:
  - [ ] In application
    - [ ] Every status
    - [ ] Modify title
    - [ ] Upload a file
  - [ ] From a card
    - [ ] Copy the link
- [ ] When I click to open a reaction/emojis to a content, the keyboard shows up.
- [ ] If there is a long history, we don’t even see the content. After the page loading we got the history first, not the content.
Applications : 
- [ ] The separation with the appcontent and the history is disturbing, there is a scroll into another scroll and sometimes it even do some random stops.
> Notes
- [ ] Content modification is a plus sign, title modification is pen sign, quite confusing. I was expecting to be able to edit the text right away.
> Discussion
- [ ] Can’t send a message.
> Profile visualization
- [ ] The picture inside the personal page is oversized and goes beyond the frame limit.
- [ ] The public name of the profile isn’t fully displayed even if there is a lot of place to display it (and no clickable tooltip).
> Space
- [ ] No clickable tooltip for space name (nor content).

p1:
- [ ] There is some miss positioning of the button "Modify a description" (Too much on the bottom right)
- [ ] Reading the title of a card (and a file too) can be hard depending on the width of the device.
- [ ] Cards are too long and tiny, like squeezed vertically. Reducing/removing the margins between the smartphone borders and the card could be nice.
- [ ] The button to open/close the menu is too small
  - [ ] the menu follows the scroll – without being smooth.
- [ ] The emoji picker takes a lot of place and hides the content – and the reaction button – 
- [ ] The way the emojis are displayed in content aren’t good. They are displayed vertically, with a wrong Z-Index, the emoji list goes behind the content.
- [ ] After selecting a Space, the left bar should close automatically.
- [ ] There should be a maximum of 3 card items in the dashboard screen so the user doesn't have to scroll forever to get to the bottom
- [ ] Sometimes the top bar disappear and will never reappears then.
- [ ] The notification wall doesn't close itself once we clicked on a notification, we have to close it manually
- [ ] The language button doesn’t update when you change the language used, so you can’t come back.
- [ ] In adminspace :
  - [ ] The panel to manage user/space,
  - [ ] the horizontal scroll isn’t clearly visible, we don’t really knowthat we have a horizontal scroll.
  - [ ] We don’t really know why is the “Plus” button for, what does it add?
  - [ ] In user section, the columns are too small and unusable (not visible).
  - [ ] Fields too large in add an account form.
  - [ ] Sometimes we can’t share file, the scroll is blocking everything.
Applications : 
- [ ] When we create a Collabora content, it takes some time to be created, and there is no visual information that the content is being created.
> Actuality
- [ ] If the text area get the focus, you won’t be able to press the send button (it is hidden behind the very bottom bar – the one which belongs to the smartphone with return button, home button, ...).
- [ ] Can’t send a comment if we are in the Actuality application.
> Agenda
- [ ] Unusable. If we don’t change the application, we should disable the agenda application on smartphone, and give a link – and a “How to…” – to link the agenda to your smartphone agenda application.

p2:
- [ ] : Every popup takes ~1/4 of my screen, on the middle (middle-up) of my screen. Which leaves me ~50 % of my screen to do something while the popup is visible.
- [ ] : Some icons in certain buttons aren’t centered
- [ ] : Remove double borders
- [ ] : There is a missing separation between the header and an application
- [ ] The term “drag&drop” may be confusing since you can’t do that on a smartphone.
- [ ] Depending on the width of the card,
- [ ] The cards don’t get the same margins based on where they are. (For example, if a card is in Recent activities the margin will be bigger than if the card were in the Space résumé which will be bigger than in the Actualities thread of a Space.)
- [ ] The alignment of the menu from the tree dots isn’t good with the card.
- [ ] After every interaction with the menu – open wall notification, open profile, … – it should hide itself.
- [ ] In space : To find the configuration – my role, create content, member list, … – I have to scroll to the bottom. Which means I can’t create anything without scrolling to the bottom.
- [ ] When we change from page to page of a content, we reload the page which made the user experiment disturbing.
- [ ] When we do a research, we got no result by default and we see the filter screen. We should see the result and have an option to do more filter
> Profile visualisation 
- [ ] The call button isn’t aligned with the informations frame nor the public name/username of the profile. In certain profile, the miss alignment make the call button slips away.
> Personal page
- [ ] Too small. If I want to edit it, I get 2,5 cm in height to see what I am doing.
> Account settings
- [ ] Fields are too large.
