### ISSUE TITLE
[META] Feat: Improvements and fixes in space management popup

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5139]
## Feature description and goals

- [ ] Think about which button should be more important between "Create" - "Create and add to spaces".
- [ ] Have a hard text warning that changes are saved
  - Improvement : "loading/validated" status
- [ ] Default text should be loading text
- [ ] To think about : how the screen reacts with a lot of spaces
- [ ] Test with add plugin in parent spaces
- [ ] The filter in the ids must not be exact 
- [ ] The "email notification" option is not aligned
- [ ] Have a highlight for a space that has just been added
- [ ] Think about how to differentiate child spaces
- [ ] Reduce the size of the lines ?

## Prerequisites

None
