### ISSUE TITLE
[META] Feat: Kanban improvements and bug fix (2)

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#5153]
## Feature description and goals

Background task:
- [ ] add functional tests
  - translations
  - create kanban
  - create column
  - create card
  - edit column 
  - edit card 

P2
- [ ] add internal links and mentions in description
- [ ] add a screen for accessing kanbans (instead of showing them as contents - have a specific tab)
- [ ] update design according to #4962 
- [ ] allow to affect several users
- [ ] show creator of a card (person that create)
- [ ] the choice of the color: there is a checkbox that has no functional interest (either I choose a color and I want it, or I don't choose one)
- [ ] the cards are not limited in height
- [ ] have all Tracim popups (not alerts or prompts) 
- [ ] column scroll 

P3
- [ ] moving/deleting a kanban is not managed by TLMs
- [ ] reload the kanban board at each modification (save?), it makes the board "blink"
- [ ] impossible to see the old revision of a kanban
- [ ] the button to change the color of a column does not update, it remains black after changing
- [ ] some ascii characters in the name of a kanban board are badly displayed in full screen
- [ ] the kanban popups is placed behind the left sidebar

Backlog (no priority)
- [ ] put a loader to move the cards
- [ ] the deadline and duration of a kanban card are not visible in the card, the information is visible in edition mode
- [ ] have a color picket that does not depend on the browser (edit Damien: I'm not sure it is a good idea to re-implement this)
- [ ] ux for kanban preview, knowing that we are probably not gonna do a real preview (illustration, don't display, ...)

## Prerequisites

For the last point it is necessary to finish issue #4962

**Comment by lebouquetin** [comment]
@gbonaspetti about this: "no TLM in the kanban (they exist but without content, so it is not possible to update the kanban without reload everything)"

The content should not come from TLM but from API. TLM are events which say "there is something new"; the information used for screen refresh should come from REST API.

This is the design defined at the beginning of TLM architecture. If the frontend does not act like this, I'd like to have a talk with @Skylsmoi you and eventually @grignards

**Comment by lebouquetin** [comment]
@gbonaspetti there are two P2 and P3 sections in the description. What is the part to analyse in order to define priorities for dev next steps?

**Comment by gbonaspetti** [comment]
> @gbonaspetti there are two P2 and P3 sections in the description. What is the part to analyse in order to define priorities for dev next steps?

Everything inside "Non-prioritized:" (before the gray line), the others (after the gray line) you already validate, but you can update if you want.

**Comment by raphj** [comment]
> P1:
> 
> Bug: No research in the description in every cards of a kanban
> Bug: Bad management of pictures in every cards

I don't know what is expected for these two issues: in both case, what is the problem and what is the expected fix? Can we clarify? (@charline-rageade)

**Comment by gbonaspetti** [comment]
> I don't know what is expected for these two issues: in both cases, what is the problem and what is the expected fix? Can we clarify?

Both fixed, the issue is not updated

**Comment by Quiwy** [comment]
I guess we can add an ux point with the vertical scrollbar overlaping buttons :
![index](https://user-images.githubusercontent.com/20048264/173313223-106f52c7-5409-41e1-a3ae-f6dc11cd02a0.png)

**Comment by PhilippeAccorsi** [comment]
PR #6168 started by Haskaris.

**Comment by lebouquetin** [comment]
This isssue is a meta issue, I put it back in the backlog (useless for tracim 4.7)

**Comment by PhilippeAccorsi** [comment]
@lebouquetin do you know what we need to do with this related PR https://github.com/tracim/tracim/pull/6168
