### ISSUE TITLE
Feat: Better handle rtl on interface

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5290]
## Feature description and goals

With the new support of Arabic langage, it is important that the interface works well on right-to-left.

- [x] change all margin-left to margin-inline-start #5295
- [x] change all margin-right to margin-inline-end #5300
- [x] change all padding-left to padding-inline-start #5296
- [x] change all padding-right to padding-inline-end #5297 
- [x] change all border-right to border-inline-end, border-left to border-inline-start, border-top-left-radius to border-start-start-radius, border-top-right-radius to border-start-end-radius, border-bottom-left-radius to border-end-start-radius, border-bottom-right-radius to border-end-end-radius #5301
- [x] change all text-align: left; to text-align: start; and all text-align: right; to text-align: end; #5302
- [x] update also the margin/padding/border/... that has 4 values, e.g. `margin 95px 0 5px 30px` #5303
- [x] Add fallback for recent proprieties #5305

## Prerequisites

None

**Comment by knodelle** [comment]
#5297 tested on branch

**Comment by knodelle** [comment]
#5301 tested on branch

**Comment by knodelle** [comment]
#5302 tested on branch

**Comment by Haskaris** [comment]
#5303 tested on branch

**Comment by knodelle** [comment]
done
