### ISSUE TITLE
Feat: META Regarding searches

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5425]
## Feature description and goals

Overhaul of the search : 
- [ ] Don't show filters by default, just simple search
- [ ] too many search parameters
- [ ] interface is not clear enough
- [ ] ask that the emphasis is put on the title of the content and not on the author

User doesn't see the point of searching by user and/or by space.
Not a dev request, rather a config request : user would like the extended search to be deactivated for them.

**Comment by Relf-Algoo** [comment]
needs discussion regarding the UX of the search tool.
