### ISSUE TITLE
[META] misc: improve alembic usage for better database migration support

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5431]
## Feature description and goals

Alembic provided interesting feature and configuration that we currently don't use. We should consider adapting our code source to use them:

- [ ] changing the migration naming in order to have migration in alphabetical order (https://stackoverflow.com/questions/53303778/is-there-any-way-to-generate-sequential-revision-ids-in-alembic), making them easier to find.
- [ ] Consider using alembic branch feature for tagging "release" version database stage
- [ ] Consider either alembic branch feature or multiple base mecanism to allow plugins to deal with their own tables.

## Prerequisites

# Extra information
- alembic branch feature: https://alembic.sqlalchemy.org/en/latest/branches.html
- mediagoblin usage of alembic branch feature for plugins: https://docs.mediagoblin.org/en/master/pluginwriter/database.html
