### ISSUE TITLE
🐛 Bug: first page load is very slow when a user is part of many spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6122]
### Tracim version

4.4.x

### Issue description

The first display of Recent Activities when logging in Tracim can be very slow when the user is part of many (>10/20) spaces.

### How to reproduce

1. Create 100 spaces
2. Add a user to those spaces
3. Login using the created user

**Comment by grignards** [comment]
The list of members of each space is loaded when logging in: one request per space, each can take between 50ms to 5000ms to process (let's take a median of 500ms). As Tracim is using HTTP/1.1 the browser limits the number of concurrent requests to 6. As those requests are initiated **before** the requests made to create the recent activities, they are processed **before** the recent activities requests, hence the delay.
If a user is part of 100 spaces: 100/6*0.5 => 8 seconds are already gone before processing any request used to create recent activities.

Those lists of members seems to be totally unused in the current code, removing them should be the quickest performance improvement.

**Comment by floreal15** [comment]
## Development status at 2023 07 11

### PR review
- [ ] rename /users/me/role_workspace endpoint to something that better match our model
- [ ] add "ROLE" in action name (check that it fixes the bug that always calls the first action reducer from reducer workspaceList)
- [ ] delete serializeRoleListProps
- [ ] add consistency in naming "RoleWorkspace" instead of "role" or "workspace" in reducer and actions
  - ex: rename serializeRole into serializeRoleWorkspace and rename action.workspaceList into action.roleWorkspaceList ...

### todo
- [ ] fix pr review
- [ ] fix unit tests
- [ ] validate with backend and api specialist the new data structure and naming "role_workspace"

**Comment by Skylsmoi** [comment]
reopened because issue isn't validated yet, it's now in "To close" on board 4.7.0
