### ISSUE TITLE
✨ Feat: Implement SAML authentication flow 

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6231]
### Feature description

This issue consolidates components of https://github.com/tracim/tracim/issues/6209 and focuses on implementing the SAML authentication flow in tracim.

### How It Works

The SAML authentication flow operates as follows:

![SAML Flow Diagram](https://github.com/tracim/tracim/assets/42064302/540fe07b-d8cb-4eaa-972d-fe9b1317cd72)

- The Identity Provider (IdP) is an external service responsible for authenticating users at the request of the Service Provider (SP), which in this case is tracim.
- The IdP has its own independent authentication mechanism.
- Both the SP and IdP must provide metadata via a specific endpoint, which contains information about endpoints and authentication requirements.

The process unfolds as follows:

1. The SP (tracim) redirects the user to the IdP, initiating the Single Sign-On (SSO) request.
2. The IdP challenges the user for authentication.
3. After authentication, the IdP redirects the user back to the SP with a POST request, containing session information. This is known as the Assertion Consumer Service (ACS) request.

From this point onward, tracim should perform the following tasks:

- Analyze the session information (e.g., check for expired requests, validate IdP's signature, etc.).
- Extract user data from the session information, such as Email, Username, and unique ID, which are referred to as attributes.
- Check if the user exists in tracim; if not, create a new user.
- Create a tracim session for the user, effectively connecting them to tracim.

De-authentication of the user is a separate task covered in https://github.com/tracim/tracim/issues/6211

#### Tasks to Complete

- [x] Implement Metadata Endpoint
- [x] Create a Generic Single Sign-On (SSO) Endpoint to redirect users to the appropriate IdP SSO endpoint
- [x] Set up the ACS Endpoint for redirection as a POST request
- [x] Match IdP-provided attributes with tracim's user fields (e.g., mail, username, unique id)
- [x] Implement user creation if they do not exist
- [x] Implement user authentication

### Related PR

https://github.com/tracim/tracim/pull/6232
