### ISSUE TITLE
✨ Feat: rename and harmonize the relation between user and space

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6252]
### description
The table is "user_worksapce". It host, currently, 2 columns "role" and "email_notification_type".
It used to be called "role" but it's not as explicit anymore since we have another column unrelated to the role and we'll probably have more unrelated columns in the futur.

We need to rename the endpoint and the related code in back and front.

The code in backend to refactor is the naming "user_role_workspaces" in user_controller.py

The code in frontend to refactor is the naming `const ROLE_WORKSPACE_LIST`

The change of endpoint name is part of the PR https://github.com/tracim/tracim/pull/6121. Code will be refactored later

### New naming

We will split the 2 concepts of Role and other properties of table user_workspace.

That way we will can use the proper naming for Role and the naming **settings** for the other properties.

Role is a subset of settings

We also aim at removing the term "member" from the code

Route:

- `/users/:user_id/workspaces/all/settings`
  - will return the list of spaces of the users where he has settings in. That means he is member of that space
  - each space will contains a property for each columns of the table user_workspace
- rename `/workspaces/:workspace_id/members` into `/workspaces/:workspace_id/roles`
  - will return a list of users and their role in the given workspace
  - will NOT return the other columns of the table user_workspace as they are supposed to be private

### TODO 
- [x] set the end point : /workspaces/{workspace_id}/members to deprecated
- [x] email summary from dashboard should use emailNotificationType from workspaceList instead of currentWorkspace.membersList
- [x] refactor the memberList property from workspaceList reducer #6243 
- [x] memberList from currentWorkspace with userRoleList 
  - [x] to confirm naming
- [x] refactor the serializeWorkspace in frontend/src/reducer/currentWorkspace.js
- [x] fix, write and unskip the unit tests for reducer knownMemberList.spec.js (added by https://github.com/tracim/tracim/pull/6275)
