### ISSUE TITLE
[META] 🐛 Bug: some fix

### ISSUE THREAD

**Issue by floreal15** [tracim/tracim#6436]
### Tracim version

4.8.0 build_128

### Issue description

- [ ] Fix path to tracimcli for mail summary in docker 

- [ ] Sed line in common.sh refer to nothing
  - Additional information: line in common.sh doesn't seems to be used anymore
```bash
sed -i "s|<PATH TO development.ini>|/etc/tracim/development.ini|g" /etc/tracim/send_summary_mails.sh
```

- [ ] Typo in a Spanish translation
  - Additional information: It generate stack trace in server log when sending mail summary
#: tracim_backend/templates/mail/summary_body_html.mak:24
msgid "{author} mentioned you in"
msgstr "{autor} le mencionó en"
```

- [ ] Mail subject should correspond to the mail send ( hourly, daily or weekly)
  - to fix: in periodic.py::_send_mail()

- [ ] Reaction enable in advanced dashboard
  - Additional information:  error 400 - Validation error of input data" when used
  - to fix : bring back the old mechanism to decide whether or not display the emoji (props showReaction)

- [ ] Notification type selection isn't taken into account if we click on the right side ( on or after the ? )
  - to fix : move the handler of the click on all the line instead of the left side

- [ ] In Spanish the notification management title overlap the selector
 - To fix: remove the white-space: nowrap;

-[] Feat : UX - the confirmation popup for the true delete is bad
  - Additional information:
## Évolution : UX - la fenêtre de confirmation de suppression définitive (en français) n'est pas centrée. 
 - Auteur : Sarah
 - Priorité : 2
 - Informations complémentaires : l'ensemble de la fenêtre est déséquilibrée (boutons pas centrés, titre sur deux lignes).


- [ ] UX - the help ( ? button) for the notification choice start behind the list before coming before
  - Additional information: blinking of the help component, not user friendly 
  - To test : force a z-index ; deactivate the appearing animation 

- [ ] Email summary log didn't indicate if the error came from an hourly, daily or weekly 
  - Additional information: script evolution or make 3 log file 
 

- [ ] UX - Card color in the logbook
  - Additional information: The mechanism from the kanban to automatically set the text color should be used in the logbook too


- [ ] Space in double
  - Additional information: In the side bar some space can be duplicate, if we click on one the other appear as active too.
  - they disappear on reload  


- [ ] In split screen, in recent activities video player go outside off the border on the right 
  - Additional information: the video player is in the iframe
  - in a resolution of 900~1000px


- [ ] UX - emoji in the Open field go outside of the border if their is to many
  - Additional information: the emojis start by reducing the title before exiting the card if their is to many
  - their is a  white-space: nowrap; on the element
  - maybe a solution is limiting the number a character 


- [ ] UX - popup for creating an office doc got a css problem with Chrome, the option exceed 


- [ ] televersement popup size isn't large and change according to the language 


- [ ] translation - the translation for the summary notification ( hourly, daily, weekly ) isn't done in most language 


- [ ] translation - the translation for the summary notification help isn't done in most language 


- [ ] translation - the translation for the logbook isn't done in most language 
  - Additional information: the element aren't translate and appear in french "Créer un journal" "Nouveau journal", "Pas encore d'évènement" and "Créer un évènement"


### How to reproduce

1

### Screenshots

_No response_

### What browsers are you seeing the problem on?

_No response_

### What devices are you seeing the problem on?

_No response_

### Related PR

_No response_

**Comment by Skylsmoi** [comment]
regressions and blocking issues have been fixed in build_129
