### ISSUE TITLE
[META] 🐛 Bug: some fix from integration test phase for 4.8.0+build_130

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6464]
## Tracim version

4.8.0 build_130

## Doc reference

https://hackmd.io/56lsiIrVQem6B5TRY3yXsg

## Issue description

- [ ] search should look for contents name translated
- [x] fix translation key for email notification type in user config
- [ ] fix popin helper for summary mail on user config / my spaces appearing on top of screen
- [ ] tlm for user changed his name or username doesn't update the mention autocomplete popin
- [ ] add scroll to summary mail autocomplete popin for mobile
- [x] improve design of logbook timeline
- [x] set min-height to emoji line in apps
- [ ] TLMs for content deleted and restored aren't displayed in history
- [ ] Missing confirm popin when deleting an item from a logbook
- [ ] Use a different icon for "restore" content from the icon of "delete" content (in button and history)
- [ ] Should we remove from elastic search index the contents that are true deleted?
  - if yes, remove the indexed upon true deletion
- [ ] Normalize border radius in DropdownMenu.jsx depending if items are `<a>` or `<button>`
- [x] Add border to edit title input in apps contents
- [x] Normalize spacing in helper popin for summary mail
- [ ] Normalize dashes "-" in apps on the line with emoji and status
- [x] Fix responsive design of message about last version in responsive apps
- [ ] Make the emoji button to never change position depending on the number of emoji
- [ ] When the logbook or kanban are in fullscreen, the "quit fullscreen" button overlaps with "last version" button and "create event" for logbook
- [ ] Fix wording in mail summary helper popin on mobile
- [ ] On app logbook, the tag's background (from the open field) doesn't change color when changing the card's background
- [ ] On app logbook, the timestamp's color doesn't when changing the card's background
