### ISSUE TITLE
[META] 🐛 Bug: issues from integration test phase for 4.9.0+build_132 (4.9.1)

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6490]
## Tracim version

4.9.0+build_132 which ended up being 4.9.1

## Doc reference

https://hackmd.io/56lsiIrVQem6B5TRY3yXsg

## Issue description

- [ ] You can save and old revision of a kanban content by clicking on an old revision while in card edition and then save
- [ ] Card date is always displayed at the ISO format regardless of user language 
- [ ] App kanban and app logbook don't have the same delete popup size
- [ ] On app kanban and logbook, the button "see more" might be not visible on mouse hover
- [ ] On sidebar, the outline of the burger button is cropped (the outline from bootstrap .btn:focus)
