### ISSUE TITLE
META: Reports from 4.10 integration tests

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6534]
Some entries are missing details, see the hackmd for further details

## p1
- [x] 🐛 Missing translation keys for web notification related elements (https://github.com/tracim/tracim/pull/6535)
- [x] https://github.com/tracim/tracim/issues/6539 (https://github.com/tracim/tracim/pull/6536)
- [x] 🐛 Translations not working properly on emails #6540 
- [x] 🐛 Read notifications are reappearing sometimes #6538  

## p2
- [ ] #6537
- [ ] 🐛 Notifications are sometime not sorted by date (a refresh solves the issue)

## p3
- [ ] 🐛 Breadcrumbs are hidden in favor of the content title (https://github.com/tracim/tracim/issues/6524)

## p4
- [ ] 🐛 When creating a user from the login page, some spaces appear multiple times (a refresh solves the issue), happens with the auto join plugin
- [ ] 🐛 Sidebar and kanban badges do not have the same style
- [ ] https://github.com/tracim/tracim/issues/6532
- [ ] 🐛 Number of mentions decrements when unsubbing, but are not recomputed when subbed (causing an inconsistency between displayed number and actual mentions), fixed by a refresh
- [ ] 🐛 Unsubbing from multiple spaces creates duplicates of notifications
- [ ] 🐛 When creating a task with newlines, they are not displayed (but are here in the actual string)

## p5
- [ ] 🐛 Outline of the sidebar's handle is truncated on firefox
- [ ] 🐛 Long news are displayed fully in recent activities
- [ ] 🐛 Disparity in left and right margins of kanban cards
